**It is assumed that you have installed Python and it is up and running.** 

### PART 1

Python is -

 1. high-level language. JS is also high level language. C, C++ are low level language. 
 
 
 2. a language with dynamic typing. C, C++ and Java are statically typed languages. JS is also dynamically typed language.
 
 
 3. OOP language
 
 
 4. a langauge where (almost) everything is an object. 
 
 
 5. a garbage collected language. C is not a garbage collected language.  
 
 
I've mentioned what kind of langauge Python is but I am mostly skipping the explanation of what these things means. They will be made clear in future. 

**Python as a calculator**

In [9]:
2+2*4, 23/11, 23%11, 23//11, 2**3 # multiplication is higer up than addition

(10, 2.090909090909091, 1, 2, 8)

In [56]:
1/0 #error 

ZeroDivisionError: division by zero

In [46]:
2-2, 3-4

(0, -1)

In [47]:
2 == 2

True

`//` is called floored division. Also referred to as integer division. The resultant value is a whole integer, though the result’s type is not necessarily int. The result is always rounded towards minus infinity: `1//2` is `0`, `(-1)//2` is `-1`, `1//(-2)` is `-1`, and `(-1)//(-2)` is `0`.

`%` is called modulo operator. 

The `%` (modulo) operator yields the remainder from the division of the first argument by the second. The numeric arguments are first converted to a common type. A zero right argument raises the `ZeroDivisionError` exception. The arguments may be floating point numbers, e.g., `3.14%0.7` equals `0.34` (since `3.14` equals `4*0.7 + 0.34`.) **The modulo operator always yields a result with the same sign as its second operand (or zero); the absolute value of the result is strictly smaller than the absolute value of the second operand.** [Source](https://docs.python.org/3/reference/expressions.html#binary-arithmetic-operations)

Python defines `pow(0, 0)` and `0 ** 0` to be `1`, as is common for programming languages.

In [4]:
22%(-3), 22//-3

(-2, -8)

In [341]:
print(22//10)
print(-22//10)
print(-22%10)

2
-3
8


**Note** - In interactive mode or in notebook, you can use `_` to access last result - 

In [260]:
2+2

4

In [261]:
_ + 6

10

#### Comparison operators

In [6]:
2 < 3, 2 <=1

(True, False)

In [8]:
3 >= 2, 4 > 5

(True, False)

In [7]:
2 != 1

True

In [49]:
2 == 3, 2 ==2 

(False, True)

#### Literals (or constant values)

 1. String literals
 2. Numeric literals
 3. Boolean literals

In [21]:
'mayank', "mayank" #constant values, string

('mayank', 'mayank')

In [12]:
2 #constant values, integer

2

In [16]:
2.33 #constant values, floating point

2.33

In [28]:
4+5j  #complex number


(4+5j)

In [29]:
True  #boolean literal

True

#### Python Keywords

Below is the list of Python keywords. They have special meaning and purposes. Don't use them as variable name. 

In [20]:
import keyword  
print(keyword.kwlist) #Python uses these words. 

['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


#### Variables 

In the context of Python, a variable is just a pointer which points to an object. Carefully note that, **a variable is not the object but a pointer to an object it is currently pointing to.** 

A variable, per se, does not have any type (checked by `type` function) or identity (checked by `id` function which returns the memory location) or any value. When you use `type` function or `id` function on a variable, you get the type and id of the object pointed by that variable.

Also note that you can always make a variable to point to any other object. In that case, the object earlier pointed by this variable is deleted (unless pointed by any other variable).





In [25]:
#variable, it can be assigned some values, values can be changed

a = 2
a, type(a), id(a)

(2, int, 739586042192)

In [26]:
a = 3.33  #now 'a' points to different value
a, type(a), id(a)

(3.33, float, 739675497456)

When we executed `a = 2`, Python created an object with value `2` of type `int` at the memory address `739586042192`. And to make this accessible to us, gave it a name `a`.

Then we ran `a = 3.33`, Python created another object with value `3.33` of type `float` at the memory address `739675497456` with name `a`.

You can see that in the former case, `a` was pointing to the object residing at memory address `739586042192` but then we made it to point to another object of different type residing at memory address `739675497456`.

This also explains what we mean when we say  "Python is dynamically typed language".

Now the question arises - what happens to the object earlier pointed by `a`? Since that object is no longer accessible (that is, not pointed by any variable), Python deletes it and frees up the memory claimed by it. (Python is garbage collected language).

So you can see that variables themselves do not have any type, identity or value. Only objects pointed by them do. 

Also note that multiple variables can point to a single object. See below - 





In [27]:
a = b = 3 

id(a), id(b)

(739586042224, 739586042224)

In [29]:
a = 4

print("a is now :- ",a)
print("b is now :- ", b)

a is now :-  4
b is now :-  3


In [30]:
id(a), id(b)

(739586042256, 739586042224)

With `a = b = 3`, we created a **single** `int` object with value `3` at memory address `739586042224` and this object is pointed to by 2 variables `a` and `b`.

Then with `a = 4`, we created another `int` object with value `4` at memory location `739586042256`. After this, earlier object can no longer be accessible through variable `a`. Since earlier object is still pointed to by `b`, it isn't deleted by Python's garbage collection mechanism. 

See another example.



In [31]:
a = 'Peter'
b = a

id(a), id(b)


(739663577136, 739663577136)

In [32]:
b = 4
print(a), id(a), id(b)

Peter


(None, 739663577136, 739586042256)

Note that before we can use any variable, we have to assign some value to them. It shouldn't come as a surprise. After all, variable has to point to some object. Without object, variable has no meaning. 

In [54]:
n  #error

NameError: name 'n' is not defined

**This section is almost completely copied from Whirlwind Tour of Python because it was so good.**


Python Variables Are Pointers - Assigning variables in Python is as easy as putting a variable name to the left of the equals (``=``) sign:
```python
# assign 4 to the variable x
x = 4
```

This may seem straightforward, but if you have the wrong mental model of what this operation does, the way Python works may seem confusing. We'll briefly dig into that here.

In many programming languages, variables are best thought of as containers or buckets into which you put data.
So in C, for example, when you write
```
// C code
int x = 4;
```
you are essentially defining a "memory bucket" named ``x``, and putting the value ``4`` into it. In Python, by contrast, variables are best thought of not as containers but as pointers. So in Python, when you write
```python
x = 4
```
you are essentially defining a *pointer* named ``x`` that points to some other bucket containing the value ``4``.
Note one consequence of this: because Python variables just point to various objects, there is no need to "declare" the variable, or even require the variable to always point to information of the same type! This is the sense in which  people say Python is *dynamically-typed*: variable names can point to objects of any type. So in Python, you can do things like this:
```python
x = 1         # x is an integer
x = 'hello'   # now x is a string
x = [1, 2, 3] # now x is a list
```
While users of statically-typed languages might miss the type-safety that comes with declarations like those found in C,
```
int x = 4;
```
this dynamic typing is one of the pieces that makes Python so quick to write and easy to read. There is a consequence of this "variable as pointer" approach that you need to be aware of.

If we have two variable names pointing to the same *mutable* object, then changing one will change the other as well! For example, let's create and modify a list:

```python
x = [1, 2, 3]
y = x
```
We've created two variables ``x`` and ``y`` which both point to the same object. Because of this, if we modify the list via one of its names, we'll see that the "other" list will be modified as well:

```python
print(y)       #output – [1,2,3]
x.append(4)    # append 4 to the list pointed to by x
print(y)       #output – [1,2,3,4] y's list is modified as well!
```

This behavior might seem confusing if you're wrongly thinking of variables as buckets that contain data. But if you're correctly thinking of variables as pointers to objects, then this behavior makes sense.
Note also that if we use "``=``" to assign another value to ``x``, this will not affect the value of ``y`` – assignment is simply a change of what object the variable points to:

```python
x = 'something else'
print(y)  # y is unchanged
```
Again, this makes perfect sense if you think of ``x`` and ``y`` as pointers, and the "``=``" operator as an operation that changes what the name points to.

Numbers, strings, and other *simple types* are immutable: you can't change their value – you can only change what values the variables point to. So, for example, it's perfectly safe to do operations like the following:
```python
x = 10
y = x
x += 5  # add 5 to x's value, and assign it to x
print("x =", x) #x=15
print("y =", y) #y=10
```
When we call ``x += 5``, we are not modifying the value of the ``10`` object pointed to by ``x``; we are rather changing the variable ``x`` so that it points to a new integer object with value ``15``. For this reason, the value of ``y`` is not affected by the operation.


**END**

In [34]:
a = None
b = 1
type(b), a.__class__

(int, NoneType)

**Note**

The `type(b)` is equivalent to `b.__class__`. Assuming you know OOP, `b.__class__` outputs the class of which `b` is an instance. 

#### Python Data types

 - `None`: This type has single value `None`. 
 - Numerics types: They are immutable.
   - Integers: 2 types of integers: Integers and Booleans 
     - `int` type for any integer. They represent all integers
     - `bool` type. Only two possible values `True` representing `1` and `False` representing `0`.
   - floats: `float` type. Represents floating value numbers such as 2.3
   - complex numbers: `complex` types. Complex numbers such as 2+3j
 - String: `str` type. Sequence of characters. These are immutable
 - Lists: `list` Lists contain orderly collection of other arbitrary Python objects. They are mutable.
 - Tuples: `tuple` Just like lists but immutable
 - Dictionaries: `dict` type. Mapping objects. Collection of `key:value` pairs. Mutable. 
 - Sets: `set` type. These represent unordered, finite sets of unique, immutable objects. They are mutable. 
 

These are the most used data types. Other data types are also available but they are rarely used hence not mentioned here.   

See below for examples of each types.


In [33]:
none_value = None
num = 1        #integer, number
flt = 2.2      #float, also a number
comp = 2+7j    #complex number
boo = True     #boolean value
st = 'abc'     #string
st1 = "afsdf"  #also a string
st2 = "111"    #also a string

foo = [1,2,'a', 'mayank', True] #a list
bar = (1,2,'a', 'mayank', True) #a tuple
baz = {'a': 1, 'b': False, 'c': 'xyz'}  #a dictionary
bam = {1,'a','b'} #a set

Good news is that these are the only data types we'll work with. 



#### Built-in types

Above we mentioned some built-in data types. Let's check `type` of each variable we defined above. 

In [40]:
type(num), type(flt), type(comp), type(boo)

(int, float, complex, bool)

In [41]:
type(st), type(st1), type(st2)

(str, str, str)

In [42]:
type(foo), type(bar), type(baz), type(bam)

(list, tuple, dict, set)

There are many other types available in Python, however, they are not necessarily data types. For example, take a built-in function `sum()` and check its type. 

In [43]:
type(sum)

builtin_function_or_method

Or a class:

In [44]:
class Test():
    pass

type(Test)

type

In [45]:
test = Test()

type(test)

__main__.Test

Above two example may stump you but don't worry. Their types aren't of immediate concern. Important point here is that there are many other possible types and they might not necessarily be data types. 

### PART 2

In this part, we'll look into numerics types, strings, lists, tuples, dictionaries and sets. 

types|iterables|sequence|mutability
------|-----|------|-------
numeric types|No|No|Immutable
string|Yes|Yes|Immutable
List|Yes|Yes|Mutable
Tuple|Yes|Yes|Immutable
Dictionaries|Yes|No|Mutable
Sets|Yes|No|Mutable

In very simple terms -

- If an object is iterable, you can iterate over its elements using `For` loop.
- If an object is sequence, you can access its elements by indexing (using `object[i]` notation)
- If an object is mutable, you can change its content without changing its identity.  

#### Numbers

In [312]:
a =  4

[i for i in dir(a) if not i.startswith('_')]

['as_integer_ratio', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']

In [12]:
some_float = 3433.121345

some_float.as_integer_ratio()

(7549513676786961, 2199023255552)

In [14]:
some_num = 121
some_num.bit_length(), bin(121)

(7, '0b1111001')

In [16]:
comp = 3+4j
comp.conjugate(), comp.imag, comp.real

((3-4j), 4.0, 3.0)

In [18]:
xy = 5
xy.denominator, xy.numerator

(1, 5)

In [15]:
import sys
n = 11
n.to_bytes(10, sys.byteorder)

b'\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00'

**Note about boolean values `False` and `True`**

In numeric contexts (for example when used as the argument to an arithmetic operator), they behave like the integers 0 and 1, respectively.

In [334]:
True == 1, True + 1

(True, 2)

In [333]:
2 - False

2

In [342]:
issubclass(bool,int)

True

In [343]:
isinstance(True, int)

True

In [6]:
bool.__bases__, int.__subclasses__()
#bool class inherits from `int` class

((int,),
 [bool,
  <enum 'IntEnum'>,
  <enum 'IntFlag'>,
  sre_constants._NamedIntConstant,
  subprocess.Handle])

In [7]:
a1 = True
a1.__class__, bool.__class__,type.__class__, int.__class__, int.__bases__, issubclass(int, object)


(bool, type, type, type, (object,), True)

In [12]:
object.__class__


type

In [15]:
nn = [1,2]
isinstance(nn, list), nn.__class__, type(nn)

(True, list, list)

In [17]:
type.__bases__, issubclass(type, object)

((object,), True)

##### Note - Lest you forget, `__class__` gives you the type of a class. `__bases__` gives you the class of which said class is a subclass. 

Complex numbers are written in the form `a+bj`. If  you want to use simply `j`, write it as `1j`.  

In [336]:
1j * 1j

(-1+0j)

Python can also deal with `NaN` ('Not a Number'), $-\infty$ and $\infty$. You simply pass the strings 'NaN', 'nan' for `NaN` and 'inf' or '-inf' for $\infty$ or $-\infty$.

In [24]:
a = float('NaN')
a

nan

In [35]:
float('inf')

inf

In [22]:
3 > float('-inf')

True

In [26]:
float('-inf') == float('-inf')


True

In [53]:
2**1000 > float('inf')

False

Note that `NaN` doesn't equal to anything, not even to itself so `==` can't be used to test equality.

In [27]:
float('NaN') == float('NaN')

False

In [54]:
a = float('NaN')

float

#### Strings

In [85]:
a = '' #empty string
b = str() #also an empty string

type(a),type(b)

(str, str)

Strings can be concatenated -

In [250]:
'Sam' + 'wise'

'Samwise'

In [251]:
name = 'Sam'
print(name + 'wise') #name is a variable which holds a string

Samwise


Below is the list of string methods. We'll talk about methods later but for the time being, just keep in mind that every object has methods which can be used by `.` notation.  

In [88]:
%pprint      
[i for i in dir('') if not '_' in i] #this is list comprehension but don't bother about it just yet

Pretty printing has been turned OFF


['capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

In [90]:
a = 'mayank'
a.capitalize()  #this is how you use method via dot notation. 

'Mayank'

You are supposed to explore every string methods. 

We can access each character of a string by subscription method. Remember that in Python, indexing starts from 0. That means first element will actually be 0th element in programming terminology. 

In [96]:
name = 'mayank'
name[0]         #subscription method

'm'

In [97]:
len(name)

6

In [151]:
name[::-1]  #string reversal through slicing 

'knayam'

In [182]:
name[:2]

'ma'

In [152]:
for i in name:
    print(i)

m
a
y
a
n
k


In [153]:
list(name)

['m', 'a', 'y', 'a', 'n', 'k']

In [155]:
sorted('peter')

['e', 'e', 'p', 'r', 't']

In [161]:
'i' in name, 'm' in name

(False, True)

white space characters such as `\n` are treated as a character 

In [238]:
print("maya\nk")

maya
k


To 'escape' this, you use `\` before anything you want to escape. For example, if you want to print `\n` as such, you escape it as shown below -

In [239]:
print("maya\\nk")

maya\nk


Alternatively, you can use *raw strings* by prefixing `r` before first quote mark - 

In [245]:
print(r'maya\nk')

maya\nk


See also - 

In [240]:
print("He said, 'Hi'")

He said, 'Hi'


In [2]:
print("He said, "Hi"") #error

SyntaxError: invalid syntax (Temp/ipykernel_5108/606407991.py, line 1)

In [243]:
#use escaping 
print("He said, \"Hi\"")

He said, "Hi"


Multi-line string

In [248]:
print('''
First enter your name
Then, your age
''')


First enter your name
Then, your age



In [249]:
print('''\
First enter your name
Then, your age
''')

First enter your name
Then, your age



Carefully note that in previous example there was a blank line while in second example, newline character was omitted because we escaped this. 

Strings are **immutable** which means, once created, you can not change the value of string. More on that later. 

In [207]:
xyz = 'mayank'
xyz[1] = 'z'    #trying to change first 'a' to 'z', error

TypeError: 'str' object does not support item assignment

#### Note 

Following is something I encountered long time after I created this notebook. I was doing an exercise is [ROSALIND](https://rosalind.info/problems/revc/) and got to learn something new. The exercise was related to finding a complement of a DNA strand. In DNA, 'A' and 'T' are complements to each other. Similarily, 'C' and 'G' are complements to each other. So if you have something like 'AAAACCCGGT', then reverse complement of this would be 'ACCGGGTTTT'. That is, first original string is reversed then each character is replaced with its complement. 

```python
#my solution
def rev_comp(s):
	s1 = s[::-1]
	table = {'A':'T','T':'A','C':'G','G':'C'}
	op = ''
	for i in s1:
		op = op + table.get(i)
	return op
```    

In [1]:
#better solution. See this docs link - https://docs.python.org/3/library/stdtypes.html#str.translate

s = 'AAAACCCGGT'
print(s[::-1].translate(str.maketrans('ACGT', 'TGCA')))

ACCGGGTTTT


In [2]:

s = 'AAAACCCGGT'
table = {'A':'T','T':'A','C':'G','G':'C'}
print(s[::-1].translate(table)) #not working? Possibly Python 2 method

TGGCCCAAAA


#### lists


In [159]:
list1 = list()  #empty list
list2 = []      #empty list
list3 = [1,2]   #non-empty list

list1,list2,list3         

([], [], [1, 2])

In [164]:
[i for i in dir(list1) if not '_' in i]

['append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']

These are the methods for list. Most of them are pretty intuitive. However, you are supposed to practice them through examples. Apart from these methods, some built-in functions such as `len()`, `sorted()` can also be applied on a list. 

Method| Return Value|
-------------|-----------|
``append(x)``|``None``
``extend(iterable)``|``None``
``insert(i,x)``|``None``
``remove(x)``|``None``
``pop([i])``|popped item
``clear()``|``None``
``index(x[, start[, end]])``| index
``count(x)``|count
``sort(*, key=None, reverse=False)``|``None``
``reverse()``|``None``
``copy()``| shallow copy of list

In [165]:
names = ['Mayank', 'Peter', 'Rajat']

len(names)

3

In [166]:
sorted(names)

['Mayank', 'Peter', 'Rajat']

In [167]:
all(names), any(names)

(True, True)

In [169]:
for i in reversed(names):
    print(i)

Rajat
Peter
Mayank


In [172]:
min(names), max(names)

('Mayank', 'Rajat')

Since elements of a list are ordered, we can access them through indexing

In [174]:
names[0]

'Mayank'

In [175]:
names[-1] # -1 means indexing starts from last element

'Rajat'

Lists can be sliced through `list[:start:stop:step]` method. `start` defaults to 0, `stop` defaults to length of list minus 1 and `step` defaults to 1.

In [18]:
values  = [3,4,3,7,8,9,5]
values[::], values[:2]

([3, 4, 3, 7, 8, 9, 5], [3, 4])

However, if `step` is negative number, `start` defaults to length of list minus 1, `stop` defaults to 0. 

In [19]:
values[::-1] #list reversal

[5, 9, 8, 7, 3, 4, 3]

In [20]:
values[:3:-1], values[6:3:-1] #slicing from end. Careful here

([5, 9, 8], [5, 9, 8])

In [200]:
values[5:3:-1]

[9, 8]

In [186]:
11 in values, 4 in values 

(False, True)

In [190]:
sum(values)

39

List can be replicated by `*` operator

In [191]:
names*3

['Mayank', 'Peter', 'Rajat', 'Mayank', 'Peter', 'Rajat', 'Mayank', 'Peter', 'Rajat']

Carefully observe the following examples

In [192]:
names

['Mayank', 'Peter', 'Rajat']

In [194]:
names1 = names
names is names1  #both are same objects

True

In [195]:
names2 = list(names)

names2 is names  #both are different objects

False

Note, however, that even though `names` and `names2` refer to 2 different lists, their contents still refer to same objects. This is **shallow copying**. Only outermost content is copied. 

In [319]:
names[1] is names2[1]

True

In [197]:
names3= names[::]

names3 is names  #both are different lists

False

In [320]:
names[1] is names3[1]

True

Lists are **mutable** which means you can change their content. 

In [208]:
random_list = [2,3,4,5]
print(id(random_list))
random_list[3] = 11
print(random_list)
print(id(random_list))

404477705856
[2, 3, 4, 11]
404477705856


You can see that the content of list has changed but its identity (value of `id()` function) hasn't.

**List comprehensions** provide a concise way to create lists. This basic syntax, then, is `[expr for var in iterable optionally 0 or more if or for clause]`, where `expr` is any valid expression, `var` is a variable name, and `iterable` is any iterable Python object.

In [260]:
[i**2 for i in range(5)]

[0, 1, 4, 9, 16]

In [261]:
#this listcomp combines the elements of two lists if they are not equal:

[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [262]:
foo = [[1,2],[3,4]]
[f for bar in foo for f in bar]


[1, 2, 3, 4]

In [263]:
[(i, j) for i in range(2) for j in range(3)]


[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]

Notice that the second `for` expression acts as the interior index, varying the fastest in the resulting list. This type of construction can be extended to three, four, or more iterators within the comprehension, though at some point code readibility will suffer!

In [273]:
colors = ['red','blue','green' ]
toys = ['car','ball','duck']

[[color, toy] for color in colors for toy in toys]

[['red', 'car'], ['red', 'ball'], ['red', 'duck'], ['blue', 'car'], ['blue', 'ball'], ['blue', 'duck'], ['green', 'car'], ['green', 'ball'], ['green', 'duck']]

In [3]:
value = [1,2,3,4,5]
name = ['Sam','Peter', 'Mac','James', 'Ryan']

[n for n, c in zip(name, value) if c > 3]

['James', 'Ryan']

#### `sorted()` vs `list.sort()`

In [264]:
some_list = [2,1,5,3]
sorted(some_list)

[1, 2, 3, 5]

In [265]:
some_list

[2, 1, 5, 3]

In [267]:
some_list.sort()
some_list

[1, 2, 3, 5]

As you can see, `sorted()` function doesn't change the original list but `list.sort()` does.

#### `list.append()` vs `list.extend()`

In [268]:
some_list

[1, 2, 3, 5]

In [269]:
some_list.append([1,2]) #this method takes an object as argument append the entire object

In [270]:
some_list

[1, 2, 3, 5, [1, 2]]

In [271]:
some_list.extend([11,12]) #this method takes an iterable as an argument and append each element of that iterable

In [272]:
some_list

[1, 2, 3, 5, [1, 2], 11, 12]

**Aside**

We have learned to use list methods like this - `some_list.sort()`. However, there is another way. You can also do `list.sort(some_list)`. Although, we haven't introduced OOP yet, but keep in mind that `some_list` is an instance of a `list` class and former is known as bound method call while later is unbound method call. [See this SO post](https://stackoverflow.com/questions/6083090/in-python-whats-difference-between-some-string-lower-and-str-lowersome-stri).

The same is true for string methods which we'll encounter in later section. `some_string.lower()` produces the same result as `str.lower(some_string)`.

#### A List Gotcha



In [1]:
a = [[None]*2]*3
a


[[None, None], [None, None], [None, None]]

In [2]:
id(a), id(a[0])

(739675491904, 739675491200)

In [3]:
id(a[0]) == id(a[1]) == id(a[2])

True


The lists `a[0]`,`a[1]` and `a[2]` are pointing to same list. They all have same `id()` value.

In [4]:
id(a[0][0]) == id(a[1][0]) == id(a[2][0])

True

In [5]:
a[0][0] =1
a

[[1, None], [1, None], [1, None]]

In [6]:
id(a), id(a[0])

(739675491904, 739675491200)

We tried to change only one element and here 3 elements are changed!

The lists `a[0]`, `a[1]`, `a[2]` are STILL pointing to same list. They all STILL have same `id()` value.
The reason behind above is that replicating a list with `*` doesn’t create copies, it only creates references to the existing objects. The `*3` creates a list containing 3 references to the same list of length two. Changes to one row will show in all rows, which is almost certainly not what you want. Try below instead - 


In [7]:
a = [None] * 3 # a = [None, None, None]
for i in range(3):
    a[i] = [None] *2 #each time a new list will be inserted

a    

[[None, None], [None, None], [None, None]]

In [8]:
a[0][0] = 1
a


[[1, None], [None, None], [None, None]]

#### One of many ways for checking for empty list

In [9]:
l = []
l and 1


[]

In [10]:
l = []
if not l:      # not l evaluates to true as empty list evaluates to false
    print("list is empty")
else:
    print(l)

list is empty


#### Inserting an element in a sorted list and ensure that list remains sorted

In [20]:
a = [1,2,4,5]

import bisect
bisect.insort(a, 3)

In [21]:
a

[1, 2, 3, 4, 5]

#### Tuples

Tuples are similar to lists except for only one difference. Unlike lists, tuples are immutable.

In [52]:
a = ()      #empty tuple
b = (1,)    #note the use of comma. Without comma 'b' will be a number
c = (1)     #not a tuple, but an integer
d = tuple() #tuple function used here
e = 1,2,'a' #also a tuple

type(a), type(b), type(c), type(d), type(e)

(tuple, tuple, int, tuple, tuple)

Tuples have following associated methods - 


In [214]:
[i for i in dir(a) if not '_' in i] #'a' is a tuple from above example

['count', 'index']

You can see tuples don't have any method such as `.append()` which can change its content. This shows the immutability of tuples. 

We saw that `a = list(b)` and `a = b[::]` create 2 different lists. Let's see see what happens in case of tuples. 

In [321]:
tuple1 = (1,2,[1])
tuple2 = tuple(tuple1)

tuple1 is tuple2

True

In [323]:
tuple3 = tuple1[::]
tuple3 is tuple1

True

We see that in case of tuples, we get same tuple. In general,

- **`b = a`** - both refers to same object, irrespective of their types.
- **`b = constructor(a)`** - if type mutable, both refer to different object otherwise same object
- **`b = a[:]`** - if type mutable, both refer to different object otherwise same object.

#### Dictonaries

Dictonaries are objects which have collections of `key:value` pairs. 

In [220]:
dict1 = {}                                     #empty dictionary
dict2 = dict()                                 #empty dictionary created by using dict() function 
dict2 = {'name': 'Peter', 'age': 35}           # 'name' & 'age' are keys and 'Peter' & 35 are their respective values


In [259]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

If keys are all strings,  it is sometimes easier to specify pairs using keyword arguments: - 


In [254]:
dict(name = 'Peter', Country ='USA')`

{'name': 'Peter', 'Country': 'USA'}

Keys can be of any immutable type. If tuples are used as keys, make sure tuples don't contain any mutable object such as a list. 

In [255]:
{(1,2):'foo'}

{(1, 2): 'foo'}

In [256]:
{(1,[2]): 'bar'}  #error

TypeError: unhashable type: 'list'

**Dict comprehension** can also be used to create a dictionary - 

In [258]:
{x:x**2 for x in [2,3,4]}

{2: 4, 3: 9, 4: 16}

Below is the list of all the methods which can be applied on a dictionary. You are supposed to practice all of them. 

In [313]:
[i for i in dir(dict1) if not i.startswith('_')] 

['clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']

Method|Return value
-------------------|----------
``clear``|``None``
``copy``|Return a shallow copy of the dictionary.
``fromkeys(iterable[, value])``|Create a new dictionary with keys from iterable and values set to value.
``get(key[, default])``|Return the value for key if key is in the dictionary, else default.
``items()``|Return a new view of the dictionary’s items ((`key`, `value`) pairs)
``keys()``|Return a new view of the dictionary’s keys. 
``popkey([, default])``|If key is in the dictionary, remove it and return its value, else return default
``popitem()``|Remove and return a (`key`, `value`) pair from the dictionary.
``setdefault(key[, default])``|If key is in the dictionary, return its value. If not, insert key with a value of default and return default.
``update([)``|Update the dictionary with the key/value pairs from other, overwriting existing keys. 
``values()``|Return a new view of the dictionary’s values

In [233]:
len(dict2)

2

In [234]:
'name' in dict2  #you can check if some key is present in dictionary

True

In [235]:
'Peter' in dict2 #there is no 'Peter' key. values can't checked for presence in dictionary 

False

In [236]:
#you can loop over dictionary keys

for i in dict2:
    print(i)

name
age


#### d[key]

In [4]:
data = {'a':1, 'b':2}
data['b']

2

In [5]:
data['b'] = 22
data

{'a': 1, 'b': 22}

#### `d | other` (for Python 3.9 and above)

Create a new dictionary with the merged keys and values of `d` and `other`, which must both be dictionaries. The values of other take priority when `d` and `other` share keys.

In [6]:
data2 = {'b':3,'c':1}

data | data2

{'a': 1, 'b': 3, 'c': 1}

#### `d |= other` (for Python 3.9 and above)

Update the dictionary `d` with keys and values from `other`, which may be either a mapping or an iterable of key/value pairs. The values of `other` take priority when `d` and `other` share keys.

In [9]:
mapping = [('c',4),('d',5)]

data2 |= mapping

data2

{'b': 3, 'c': 4, 'd': 5}

### Sets


In [229]:
set1 = set()      #empty set using set() function
set2 = {1,2,3,4}  #set
no_set1 = {}      #not a set
list5 = [1,2,3,1] 
set3 = set(list5) ##will prepare a set by removing duplicate items

print(set3)

{1, 2, 3}


In [315]:
[i for i in dir(set1) if not i.startswith('_')] 

['add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']

In [230]:
4 in set3, 3 in set3

(False, True)

In [231]:
len(set3)

3

In [232]:
set3[1]  #indexing doesn't work with sets

TypeError: 'set' object is not subscriptable

### Some code snippets


In [326]:
#a list of lists is given. You want to create a list consisting of unique items.

lol = [['a','b','c'],['b','c','d'],['d','e']]
a = set().union(*lol)
list(a)

['b', 'e', 'c', 'd', 'a']

In [327]:
#merging two dictionaies into one

a = {'b':3, 'c':4}
b = {'b':7,'d':9}
merged = {**a, **b} #for 3.5++
merged              #Notice for key b, lattermost value was used.

{'b': 7, 'c': 4, 'd': 9}

In [328]:
# Combining 2 lists - One list as keys and items from other list are grouped as values

a = ['jan','jan', 'feb', 'mar', 'feb']
b = [1,2,3,4,5]
c = {}
for x, y in zip(a,b):
    c.setdefault(x,[]).append(y)
    
c    

{'jan': [1, 2], 'feb': [3, 5], 'mar': [4]}

### PART 3

Before we move to loops and control flows, we need to understand **Truth value testing.**

Any object can be tested for truth value for use in an `if` or `while` condition or as operand of the Boolean
operations. Every object is either `True` or `False`. The general intuition is that `False` denotes zero or emptiness while `True` denotes some value. 

Here are most of the built-in
objects considered false:

 - constants defined to be false: `None` and `False`.
 - zero of any numeric type: `0`, `0.0`, `0j`, `Decimal(0)`, `Fraction(0, 1)`
 - empty sequences and collections: `''`, `()`, `[]`, `{}`, `set()`, `range(0)`

Operations and built-in functions that have a Boolean result always return `0` or `False` for false and `1` or
`True` for true, unless otherwise stated. 

(Important exception: the Boolean operations `or` and `and` always return one of their operands. Explained later)

We can use built-in `bool()` function to test the truth value. See following examples - 

In [68]:
a = [1] #non-empty list and truth value is True
b = []  #empty list, hence truth value is False
c = {}  #empty dictionary, False
d = ''  #empty string
e = 'mayank' #non-empty string, True
f = True #always 
g = False #always False
h = None #False
i = 0 #zero is False

bool(a),bool(b),bool(c),bool(d),bool(e),bool(f),bool(g),bool(h),bool(i)

(True, False, False, False, True, True, False, False, False)

#### Boolean Operations - **`and`, `or`, `not`**

These are the Boolean operations, ordered by ascending priority:

|Operation            |Result|Notes|
|---------------------|------|-----|
|`x or y`|if `x` is false, then `y`, else `x`|1|
|`x and y`|if `x` is false, then `x`, else `y`|2|
|`not x`|if `x` is false, then `True`, else `False`|3|


1. This is a short-circuit operator, so it only evaluates the second argument if the first one is false.
2. This is a short-circuit operator, so it only evaluates the second argument if the first one is true.
3. `not` has a lower priority than non-Boolean operators, so `not a == b` is interpreted as `not (a == b)`, and `a == not b` is a syntax error.

In [69]:
print(3 and 5)     #'x and y' operation. 'x' is not false so it returns 'y', that is, 5. 
print(5 and 3)
print(5 and False)
print(False and 5)
print(None and 5)
print(0 and 5)

5
3
False
False
None
0


In [70]:
print(3 or 5)      # 'x or y' operation. if 'x' false, 'y' is output. Otherwise 'x' is output. 
print([] or 3)
print(0 or 3)
print(3 or 0)
print(False or 3)
print(0 or False)

3
3
3
3
3
False


In [71]:
1 and 0 or 3 #left to right evaluation

3

While we are at it, let us also look into `&` and `|` operators. They are similar to `and` and `or` but they operate on bits of objects rather than on objects themselves. 

In [77]:
3 and 122, 3 & 122  #see the difference


(122, 2)

In [83]:
print(bin(3))
print(bin(122))
print(bin(3 & 122))


0b11
0b1111010
0b10


In [1]:
a = [1,2,3]
b = [2,0,4]

a and b

[2, 0, 4]

In [2]:
a & b

TypeError: unsupported operand type(s) for &: 'list' and 'list'

In [287]:
import numpy as np 
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [288]:
A or B #error

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### Python ternery operator

In [289]:
a = 1
b = 2
1 if a > b else -1


-1

In [70]:
a,b,c = [1,2,3]
a < b == c


False

In [72]:
a < b and b < c

True

In [292]:
a,b,c = [2,3,3]
a < b or b < c

True

In [293]:
d = a or b or c
d

2

In [294]:
d =  a and b and c
d


3

### `if-elif-else` conditions

With `if`, `elif` and `else` are optional. 

Syntax is:

```Python
if <exp>:         
    <code block>
elif <exp>:
    <code block>
else:
    <code block>
```

    

In [68]:
if 1:
    print('Hi')
    
    

Hi


In [69]:
if []:
    print('Nothing is printed')

In [41]:
if False:
    print("nothing will be printed")

In [42]:
if True:
    print("HELLO!")

HELLO!


In [284]:
value  =  5

if value < 6:     # 5 < 6 evaluates to True
    print('Fine')

Fine


In [285]:
age = int(input("Enter age:\n"))

if age < 40:                  #55 < 40 evaluates to False so 'if' clause won't be executed
    print("You are young")
else:             
    print("No more young!")

Enter age:
55
No more young!


In [286]:
value =  3

if value in [2,3,4,5,6]:
    print("value is in container")

value is in container


In [40]:
nums = [2,3,4]

for i in nums:
    if i%2==0:
        print('{} is even number'.format(i))
    else:
        print('{} is odd number'.format(i))
    

2 is even number
3 is odd number
4 is even number


In [55]:
marks = -90

if marks >=0 and marks <= 50:
    print("Your marks are not good")

elif marks > 50 and marks <= 75:
    print("Your marks are good")
    
elif marks > 75 and marks <= 100:     #using 'else'clause here can cause problems
    print("Your marks are excellent!")

In codes where you are using `elif` clause(s), be careful that the condition you are testing should be =`True` in exactly one of `if-elif-else` clauses. 

Can you see if there is any problem in following code?

```Python
marks = -90

if marks >=0 and marks <= 50:
    print("Your marks are not good")

elif marks > 50 and marks <= 75:
    print("Your marks are good")
    
else:     
    print("Your marks are excellent!")
```



In [49]:
#LOL!!

marks = -90

if marks >=0 and marks <= 50:
    print("Your marks are not good")

elif marks > 50 and marks <= 75:
    print("Your marks are good")
    
else:     #using 'else'clause here can cause problems
    print("Your marks are excellent!")

Your marks are excellent!


### `for` loop

Syntax is

```Python
for i in iterable:
    #do something with i
```    
Runs a block of code for each element in a given sequence.


In [274]:
values = [1,2,3,4]

for i in values:
    print(i*i)

1
4
9
16


In [2]:
mapping = {'Sam': 10, 'Peter': 8, 'Sean':6}

for i in mapping:        #iteration over dictionary keys
    print(mapping[i]*3)
           

30
24
18


In [275]:
for i in range(1,5):
    if i == 2:
        pass
    else:
        print(i)

1
3
4


In [276]:
for i in range(7):
    if i == 4:
        continue
    else:
        print(i)

0
1
2
3
5
6


In [277]:
for i in range(7):
    if i == 4:
        break          #this will terminate the loop`
    else:
        print(i)

0
1
2
3


### `for - else` 

In [283]:
listing = [1,2,3,6,8]
for i in listing:
    if i == 6:
        print(i)
        break    
else:
    print('not there')  


6


In above example, `else` is associated with `for` clause and it is executed if `break` is not executed.

### `while` loop

Syntax is 

```Python
while <expression>:
    code block
```

Code block will be executed as long as *expression* is `True`.

In [278]:
a = 0
while a <6: 
    print(a)
    a+=1

0
1
2
3
4
5


In [280]:
#while True introduces infinite loop, can only be terminated via `break` statement

while True:
    name = input("Enter your name:\n")
    if name == "Mayank":
        print("Hi, %s" %name)
        break

Enter your name:
peter
Enter your name:
Mayank
Hi, Mayank


#### `while-else-break` loop

Run example given below. Notice two things. First, notice `else` clause is associated with `while` clause. Second, notice `break` statement and how it affects the execution of `else` clause. `else` clause is run only when `break` statement is not executed. 

In [281]:
a = 1
while (a < 3):
    string =  input("input your name in small letters:\n")
    if string == 'mayank':
        print("Hi %s" %string) 
        break
    a = a + 1

else:
    print("Sorry!")

input your name in small letters:
sam
input your name in small letters:
peter
Sorry!


In [282]:
n = -1
while n < 5:
    n =  n + 1
    if n == 2:
        continue
    print(n)

0
1
3
4
5


`continue` makes program do nothing for current iteration, rather it makes program to jump to next iteration.

### PART 4

This is the part I want to introduce at later part of the course because it introduces design features and some subtle concepts which novices may not be able to fully understand. 

#### Everything is an object 

Every variable you define is an object. Every function, built-in or user-defined, is an object. Every class is an object. Every instance of a given class is an object. This also means you can 'move around' them. You can assign them to variables, you can pass them to functions, functions can return them and so on. 

Also every object has some associated characterstics (called attributes) and associated behaviours (called methods). We can access attributes or apply methods on object via `.` notation. 

     obj.attribute
     obj.method()

Every object has a type, an identity and a value. 

**Following section is credited to Jake VanderPlas**

Python is an object-oriented programming language, and in Python everything is an object.
Let's flesh-out what this means. Earlier we saw that variables are simply pointers, and the variable names themselves have no attached type information. This leads some to claim erroneously that Python is a type-free language. But this is not the case!
Consider the following:
```python
x = 4
type(x) #int
x = 'hello'
type(x) #str
x = 3.14159
type(x) #float
```

Python has types; however, the types are linked not to the variable names but *to the objects themselves*. In object-oriented programming languages like Python, an *object* is an entity that contains data along with associated metadata and/or functionality.

In Python everything is an object, which means every entity has some metadata (called *attributes*) and associated functionality (called *methods*). These attributes and methods are accessed via the dot syntax.
For example, before we saw that lists have an ``append`` method, which adds an item to the list, and is accessed via the dot 
("``.``") syntax:
```python
L = [1, 2, 3]
L.append(100)
print(L)     # L = [1, 2, 3, 100]
```
While it might be expected for compound objects like lists to have attributes and methods, what is sometimes unexpected is that in Python even simple types have attached attributes and methods. For example, numerical types have a ``real`` and ``imag`` attribute that returns the real and imaginary part of the value, if viewed as a complex number:  x 
```python
x = 4.5
print(x.real, "+", x.imag, 'i')  # 4.5 + 0.0i
```
Methods are like attributes, except they are functions that you can call using opening and closing parentheses. For example, floating point numbers have a method called ``is_integer`` that checks whether the value is an integer:
```python
x = 4.5
x.is_integer() #False
x = 4.0
x.is_integer() #True
```

When we say that everything in Python is an object, we really mean that *everything* is an object – even the attributes and methods of objects are themselves objects with their own ``type`` information:
```python
type(x.is_integer)       #builtin_function_or_method
```

#### Mutability and Immutability

So far we have seen that strings and tuples are immutable while lists are mutable. Although we might have developed generally accurate understanding of mutable/immutable objects, we better look at it more closely. 

#### Some Excrepts from Python Documentations

##### Data Model

Objects are Python’s abstraction for data. All data in a Python program is represented by objects or by
relations between objects. (In a sense, and in conformance to Von Neumann’s model of a “stored program
computer,” code is also represented by objects.)
Every object has an identity, a type and a value. An object’s identity never changes once it has been created;
you may think of it as the object’s address in memory. The `is` operator compares the identity of two
objects; the `id()` function returns an integer representing its identity.

---
(*following section hints what we mean by mutability*)

An object’s type determines the operations that the object supports (e.g., “does it have a length?”) and also
defines the possible values for objects of that type. The `type()` function returns an object’s type (which is
an object itself). Like its identity, an object’s type is also unchangeable.1
The value of some objects can change. Objects whose value can change are said to be mutable; objects
whose value is unchangeable once they are created are called immutable. (The value of an immutable
container object that contains a reference to a mutable object can change when the latter’s value is changed;
however the container is still considered immutable, because the collection of objects it contains cannot be
changed. So, immutability is not strictly the same as having an unchangeable value, it is more subtle.) An
object’s mutability is determined by its type; for instance, numbers, strings and tuples are immutable, while
dictionaries and lists are mutable.
Objects are never explicitly destroyed; however, when they become unreachable they may be garbagecollected.
An implementation is allowed to postpone garbage collection or omit it altogether — it is a
matter of implementation quality how garbage collection is implemented, as long as no objects are collected
that are still reachable.

---
...Some objects contain references to other objects; these are called containers. Examples of containers are
tuples, lists and dictionaries. The references are part of a container’s value. In most cases, when we talk
about the value of a container, we imply the values, not the identities of the contained objects; however,
when we talk about the mutability of a container, only the identities of the immediately contained objects
are implied. So, if an immutable container (like a tuple) contains a reference to a mutable object, its value
changes if that mutable object is changed.

-----
Types affect almost all aspects of object behavior. Even the importance of object identity is affected in
some sense: for immutable types, operations that compute new values may actually return a reference to
any existing object with the same type and value, while for mutable objects this is not allowed. **E.g., after
`a = 1`; `b = 1`, `a` and `b` may or may not refer to the same object with the value one, depending on the
implementation, but after `c = []; d = []`, `c` and `d` are guaranteed to refer to two different, unique, newly
created empty lists. (Note that `c = d = []` assigns the same object to both `c` and `d`.)**

In [304]:
a = 1
b = 1

a is b

True

In [305]:
a = 300
b = 300

a is b

False

**Note** - For values between [-5,256], `a` and `b` will be identical.

In [301]:
a, b = [],[]
a is b

False

#### Mutability of Tuples

In [337]:
t1 = (1,2,[3,4])

print(t1)
print("id of t1 is %d" %id(t1))
print("id of t1[-1] is %d" %id(t1[-1]))

t1[-1].append(5)

print("now t1 is ", t1)
print("now id of t1 is %d" %id(t1))
print("now id of t1[-1] is %d" %id(t1[-1]))


(1, 2, [3, 4])
id of t1 is 404495510080
id of t1[-1] is 404478705856
now t1 is  (1, 2, [3, 4, 5])
now id of t1 is 404495510080
now id of t1[-1] is 404478705856


Tuples are immutable but above we can see it got 'mutated'. This example shows how tuples can be mutable if one of its elements is of mutable type. In this example, original and final tuple still have same id.

This also illustrates the situation in which the value of a tuple changes as result of changes to a mutable object referenced in it. What can never change in a tuple is the identity of the items it contains. Also – 

In [338]:
t = (1,2,[30,40])
t[2] += [50,60] #id of list won't change, hence tuple will 'mutate'


TypeError: 'tuple' object does not support item assignment

In [339]:
t

(1, 2, [30, 40, 50, 60])

In [340]:
t[2] = t[2] +[90] #won't work as id of list will change which isn't allowed as tuple is immutable

TypeError: 'tuple' object does not support item assignment

#### += Operation on Mutable Types
For any operator "``■``", the expression ``a ■= b`` is equivalent to ``a = a ■ b``, with a slight catch.
For mutable objects like lists, arrays, or DataFrames, these augmented assignment operations are actually subtly different than their more verbose counterparts: they modify the contents of the original object rather than creating a new object to store the result.

In [306]:
s = [1,2,3]
print(id(s))
s = s + [1]
print(id(s))  #id of s changed
s+=[2]
print(id(s))  #id doesn't change

404495335936
404495335680
404495335680


#### Aside: Floating Point Precision

One thing to be aware of with floating point arithmetic is that its precision is limited, which can cause equality tests to be unstable. For example:

In [307]:

float(2**53) == float(2**53) + 1

True

In [308]:
.1 + .2

0.30000000000000004

Why is this the case? It turns out that it is not a behavior unique to Python, but is due to the fixed-precision format of the binary floating-point storage used by most, if not all, scientific computing platforms. All programming languages using floating-point numbers store them in a fixed number of bits, and this leads some numbers to be represented only approximately. We can see this by printing the three values to high precision:


In [309]:
print("0.1 = {0:.17f}".format(0.1))
print("0.2 = {0:.17f}".format(0.2))
print("0.3 = {0:.17f}".format(0.3))

0.1 = 0.10000000000000001
0.2 = 0.20000000000000001
0.3 = 0.29999999999999999


We're accustomed to thinking of numbers in decimal (base-10) notation, so that each fraction must be expressed as a sum of powers of 10:
$$
1 /8 = 1\cdot 10^{-1} + 2\cdot 10^{-2} + 5\cdot 10^{-3}
$$
In the familiar base-10 representation, we represent this in the familiar decimal expression: $0.125$.

Computers usually store values in binary notation, so that each number is expressed as a sum of powers of 2:
$$
1/8 = 0\cdot 2^{-1} + 0\cdot 2^{-2} + 1\cdot 2^{-3}
$$
In a base-2 representation, we can write this $0.001_2$, where the subscript 2 indicates binary notation.
The value $0.125 = 0.001_2$ happens to be one number which both binary and decimal notation can represent in a finite number of digits.

In the familiar base-10 representation of numbers, you are probably familiar with numbers that can't be expressed in a finite number of digits.
For example, dividing $1$ by $3$ gives, in standard decimal notation:
$$
1 / 3 = 0.333333333\cdots
$$
The 3s go on forever: that is, to truly represent this quotient, the number of required digits is infinite!

Similarly, there are numbers for which binary representations require an infinite number of digits.
For example:
$$
1 / 10 = 0.00011001100110011\cdots_2
$$
Just as decimal notation requires an infinite number of digits to perfectly represent $1/3$, binary notation requires an infinite number of digits to represent $1/10$.
Python internally truncates these representations at 52 bits beyond the first nonzero bit on most systems.

This rounding error for floating-point values is a necessary evil of working with floating-point numbers.
The best way to deal with it is to always keep in mind that floating-point arithmetic is approximate, and *never* rely on exact equality tests with floating-point values.

#### Iterable vs Iterator

Iterable is a collection while iterator is a stream. In iterable, all items are availble at any and all the time. And of course, you can iterate over them. However, iterator doesn't have all the items available. It gives you one item at a time on the fly and keep track of its present state. An object is called iterable if you can get an iterator for it. To convert an iterable into a iterator, pass it to `iter()` function which returns an iterator object.

In technical terms, iterable has `__iter__` method defined and iterator has `__next__` method defined for it. 

Successive calls to `next(iterator)` function return successive elements. After iterator is exhausted, it raises `StopIteration` exception. 





In [63]:
name = 'Mayank'

'__iter__' in dir(name)

True

In [64]:
a = iter(name)

'__next__' in dir(a)

True

In [65]:
next(a)

'M'

In [66]:
next(a)

'a'

In [67]:
next(a), next(a), next(a), next(a), next(a)

StopIteration: 

### PART 5

### Error handling and Exceptions

People commit all sort of mistakes when they write programs (or do anything else). If you haven't, either you are a God or you haven't tried anything. If you have come this far in your journey of learning Python, you must have seen fair amount of error messages such as `TypeError`, `SyntaxError`, `ValueError` or `NameError`. Although Python tries to help you by showing what kind of mistake you have committed (*by raising an exception*) but let's admit that seeing such message(s) isn't exactly encouraging or pleasant. 

In this section, we'll learn how to handle these errors and let our program complete gracefully regardless of whether an excception occured or not. First, let's see some examples of errors -  

In [56]:
For i in range(5)  #SyntaxError
    print(i)


SyntaxError: invalid syntax (<ipython-input-56-22fe0292925e>, line 1)

In [57]:
print(aa) #variable aa isn't defined

NameError: name 'aa' is not defined

In [58]:
1/0  #division by 0 is not allowed

ZeroDivisionError: division by zero

In [59]:
a = 0
a.value

AttributeError: 'int' object has no attribute 'value'

In [60]:
def f(a):
    a.append(2)
    
f(2)    

AttributeError: 'int' object has no attribute 'append'

Rather than showing (or seeing) these irritating messages, it'd be much nicer if we try to handle them within our program. It is not that you'll be able to avoid these errors, but at least you (or other users) will see much better output. 

Let's see how some of above programs can be rewritten to properly handle the errors ()- 

In [62]:
try:
    1/0

except ZeroDivisionError:
    print('Division by 0 is not allowed.')

Division by 0 is not allowed.


In [63]:
try:
    a = 0
    print(a.value)
    
except AttributeError as e:
    print(e)
    print("Please check for the object's attribute list")
    

'int' object has no attribute 'value'
Please check for the object's attribute list


You can see that our programs still produced errors but they were handled rather nicely. 



**Note about `SyntaxError`:**

Unlike other cases we have seen above, `SyntaxError` can't be handled. `SyntaxError` is caught when your program is parsed while errors like `AttributeError` happen when your program is exceuted. The later type of errors are called **exceptions** and we'll learn to handle these exceptions. 

Oh, just like everything else in Python, exceptions, too, are objects. 

### `try` statement


The `try` clause is followed by -

 - one or more `except` clauses (optionally followed by exactly one `else` clause)
 - (optionally) exactly one `finally` clause
 
 
The syntax is as follows - 

```Python
try:
    statement(s)
except [expression [as target]]:
    statement(s)
[else:
    statement(s)]
[finally:
    statement(s)]
```
<br>

**Note** Square brackets `[]` in documentations or syntax descriptions tell us that part enclosed by `[]` is optional. For example, if you read the [Python documentation](https://docs.python.org/3.9/library/functions.html#input) of `input()` function, you'll see that the function signature of this function is ` input([prompt])`. What it says that the parameter `prompt` is optional. So `[]` around `else` and `finally` clauses in description of `try-except-else-finally` syntax indicates that these clauses are optional. 

<br>

The `except` clauses are where exceptions are handled and therefore they are called *exception handlers*. Notice that in syntax description `except` statement is followed by `[expression [as target]]`. The `except` clause handles the exception propagated from `try`  only if exception name mathes the `expression` part in `except` statement. `expression` part may be a single class or a tuple of classes. The optional `target` is an identifier that names a variable that Python binds to the
exception object just before the exception handler executes. A handler can also obtain the current exception object by calling the `exc_info` function of module `sys`.

I can guess the above description is a bit terse. So let us go through some examples.

In [67]:
inp = input('Enter any number\n')
try:
    a =  int(inp)
    print(a)

except:
    print('Enter valid input.')
    

Enter any number
gg
Enter valid input.


Consider above example. The main part of our code resides in `try` clause. Now come to `except` clause. Any exception raised in `try` clause will be handled in `except` clause. If `try` clause doesn't raise any exception, `except` clause won't be executed. While running this code, we provided a string `gg` as input which obviously is an invalid input because it can't be converted to an integer. Because of this, an exception is raised which is caught and handled by `exception` clause. The output doesn't tell but `try` clause raised `ValueError` which we handled.

Since `exception` clause in above code doesn't have any `expression` part, it will handle every exception raised by `try` clause. Is that a good thing? Actually no.

See following example- 



In [66]:
inp = input('Enter any number\n')
try:
    a =  int(inp)
    print(aaa)

except:
    print('Enter valid number.')

Enter any number
'44'
Enter valid number.


Given our program, `'44'` was valid input and yet our program asked us to provide valid number. What went wrong?

The problem is that in 4th line of program, I mistyped `a` as `aaa` in `print` function which eventually raised the `NameError`. Since our `except` clause was designed to handle all exceptions in only one way, it handled this exception exactly the same way it earlier handled `ValueError`. Not a good thing. So what can we do to improve this? We explicitly mention the exception we want to handle in `except` clause as shown in below example -  

In [68]:
inp = input('Enter any number\n')
try:
    a =  int(inp)
    print(aaa)

except ValueError:
    print('Enter valid number.')
    
except NameError:
    print('undefined variable')
    
except:
    print("some other error")

Enter any number
54
undefined variable


This is better. 

We provided 3 `except` clauses and first 2 clause's `expression` part explicitly mentions the exception we want to handle. Since raised `NameError` matched the `expression` value of second `except` clause, this clause was executed. **Note that `except` clauses are evaluated in order**. If bare `except` clause (third clause in above example) had come before other clauses, it would have handled the `NameError`. This is not what we would have wanted. 

If you wish, you can print the error message generated by exception. This is done by providing `target` variable (in `except [expression [as target]]:` part). 

In [69]:
inp = input('Enter any number\n')

try:
    a =  int(inp)
    print(aaa)

except ValueError:
    print('Enter valid number.')
    
except NameError as err:
    print(err)
    print('undefined variable')
    
except:
    print("some other error")

Enter any number
44
name 'aaa' is not defined
undefined variable


`except` clause can handle multiple exceptions. To do this, you simply pass a tuple of exception names as an argument to `except`:

```Python
try:
    <code block>
except (NameError, ValueError):
    <code block>
```    

#### `else` clause

We mentioned we can also provide optional `else` clause. This is executed only when `try` clause is executed normally. If `try` clause raises any exception, `else` clause won't run. Also, if any of `break`, `continue` or `return` statement (if present) in `try` clause is executed, `else` clause won't run. See following examples -   

In [74]:
inp = input('Enter any number\n')
try:
    a =  int(inp)
    print(a)

except ValueError:
    print('Enter valid number.')
    
except NameError as err:
    print(err)
    print('undefined variable')
    
except:
    print("some other error")
    
else:
    print("'try' clause executed normally")
          

Enter any number
55
55
'try' clause executed normally


In [75]:
inp = input('Enter any number\n')

try:
    a =  int(inp)
    print(a)

except ValueError:
    print('Enter valid number.')
    
except NameError as err:
    print(err)
    print('undefined variable')
    
except:
    print("some other error")
    
else:
    print("'try' clause executed normally")
          

Enter any number
hfg
Enter valid number.


In [3]:
while True:

    try:    
        secret = int(input("Enter secret number"))
        if secret == 44:
            print("You are granted entry")
            break

    except ValueError:
        print("Enter valid number")
    
    else:
        print("Nothing will be printed")

Enter secret number44
You are granted entry


In [4]:
#break is executed and yet else clause ran???

try:

    while True:    
        secret = int(input("Enter secret number"))
        if secret == 44:
            print("You are granted entry")
            break

except ValueError:
    print("Enter valid number")
    
else:
    print("Nothing will be printed")

Enter secret number44
You are granted entry
Nothing will be printed


In [10]:
def f(a,b):
    try:
        a.append(b)
        print(a)    #if return a is used here, else clause won't run
    
    except AttributeError:
        print('first argument has to be a list')
    
    else:
        print('test message')

 #exception  raised so else clause won't run       

In [11]:
f(2,3)

first argument has to be a list


In [12]:
f([],3) #no exception raised, else clause executed

[3]
test message


In [15]:
def f(a,b):
    try:
        a.append(b)
        return a      #if this return executed, function will be exited 
    
    except AttributeError:
        print('first argument has to be a list')
    
    else:
        print('test message')

In [16]:
f([],2)

[2]

A note about above example, functions exit as soon as they execute `return` statement. It doesn't matter if your rest of the code was executed or not. 

In [19]:
def f(a):
    return a
    print(a*2)

In [20]:
f(32)

32

In [60]:
import sys

try:
    f = open('myfile1.txt')
    s = f.readline()
    i = int(s.strip())
except OSError as err:
    print("OS error: {0}".format(err))
except ValueError:
    print("Could not convert data to an integer.")
except:
    print("Unexpected error:", sys.exc_info()[0])
    raise

OS error: [Errno 2] No such file or directory: 'myfile1.txt'


-  Rrun this program w/o any existing 'myfile1'. It will raise `OSError`.
-  Save a text file named 'myfile' with some text content and then run the program. It will raise `ValueError`.
-  Type 'inta' in place of 'int' in `int()` in `try` clause, then run the program. It will raise `Unexpected error` in third `except` clause. Also notice the use of `sys.exc_info()` function,
-  If we omit `raise`, exception will still be raised but without any additional details. Try running the program with and w/o `raise` in third `except` clause.


#### `finally` clause

 - There can only be at most one `finally`clause. 
 - These clauses are always executed regardless of what happens in other clauses. If an exception is raised in `try` clause and is not handled, it is saved until `finally` is executed and then it is reraised. However, if `return`, `break` or `coninue` is executed in `finally` clause, the saved exception is discarded.
 - If a function has `try-finally` suit of clauses with `return` statements, the return value and any exception raised in `try` clause will be discarded and `return` value of `finally` clause will be used.  
 - If the `try` statement reaches a `break`, `continue` or `return` statement, the `finally` clause will execute just prior to the `break`, `continue` or `return` statement’s execution.


In real world applications, the `finally` clause is useful for releasing external resources (such as files or network connections), regardless of whether the use of the resource was successful.

In [21]:
try:
    1/0
    
except ZeroDivisionError:                #exception is handled
    print("division by 0 not allowed")
    
finally:
    print("this will always be executed at the end")
    

division by 0 not allowed
this will always be executed at the end


In example below,the `ZeroDivisionError` exception is raised but is not handled. So this exception is saved until the execution of `finally` clause. It is reraised after `finally` clause is executed.

In [22]:
try:
    1/0
    
except NameError:                
    print("name is not defined")
    
finally:
    print("this will always be executed at the end")
    

this will always be executed at the end


ZeroDivisionError: division by zero

In [23]:
def f(a,b):
    
    try:
        return  a/b
    finally:
        return 42
    
    

In [25]:
f(3,2)

42

In [26]:
f(1,0)

42

In [33]:
def demo1():
    try:
        raise RuntimeError #"To Force Issue"
    except:
        return 1
    else:
        return 2
    finally:
        return 3

def demo2():
    try:
        try:
            raise RuntimeError #"To Force Issue"
        except:
            return 1
        else:
            return 2
        finally:
            return 3
    except:
        print(4)
    else:
        print(5)
    finally:
        print(6)


In [34]:
demo1()

3

In [35]:
demo2()

6


3

#### Raising forced exception and `raise` statement

You can also force a specified exception to occur by using `raise` statement - 


In [37]:
raise NameError #equivalent to calling `raise NameError()`


NameError: 

In [38]:
raise NameError("Hi")

NameError: Hi

Of course, we can handle these raised errors - 

In [40]:
try:
    raise NameError("Forced error")
except NameError as e:
    print(e)
    


Forced error


We saw earlier that a bare `except` clause will handle every exception raised in `try` clause. This way, although exceptions are handled, we get no information as to what exception is handled by a bare `except` clause. We can use bare `raise` statement to re-raise the exception. Also, we can use bare `raise` to reraise any exception even though it was handled.

In [41]:
try:
    1/0
    
except ZeroDivisionError:
    print("Something bad happened")
    raise

Something bad happened


ZeroDivisionError: division by zero

In [42]:
try:
    1/0
except:
    raise

ZeroDivisionError: division by zero

#### `sys.exc_info()`

The `exc_info()` function from `sys` returns a tuple `(type, value, traceback)` regarding the most recent exception caught by an `except` clause

In [55]:
import sys

try:
    1/0
    
except:
    print(sys.exc_info()[0])
    print(sys.exc_info()[1])
    print(sys.exc_info()[2])

<class 'ZeroDivisionError'>
division by zero


In [43]:
def func():
...     raise IOError
...
>>> try:
...     func()
... except IOError as exc:
...     raise RuntimeError('Failed to open database') from exc

RuntimeError: Failed to open database

#### Defining custom exceptions

In addition to built-in exceptions, it is possible to define custom exceptions through class inheritance. For instance, if you want a special kind of `ValueError`, you can do this:

In [56]:
class CustomError(ValueError):
    pass

raise CustomError('You are wrong because I say so.')



CustomError: You are wrong because I say so.

In [57]:
a,b = 1,0

from contextlib import suppress
with suppress(ZeroDivisionError):
    print(a/b)

# error suppressed


#### Exception hiearchy

Every exception which is raised is an instance of a class derived form `BaseException`. For example, `AttributeError` is subclassed from `Exception` class which in turn is subclassed from `BaseException`. 

[Exception hiearchy](https://docs.python.org/3.9/library/exceptions.html#exception-hierarchy)

### Object Oriented Programming

Phew! OOP finally!


You may think that you don't know anything about OOP or classes but guess what, you have been using these concepts all along. Practically every program you ever wrote in Python has implicitly used elements of OOP and classes. For examples - when you do something like `a = list(b)` or `some_list.append()` or `b = string(c)` or `for i in range(10):`, you were actually using classes. And let me admit: I kind of lied when I said that `list()`, `tuple()`, `range()` and `set()` are built-in functions. These aren't actually functions. They are classes but we pretended as if they were functions (because both classes and functions are *callables*). 


It is not like there are problems which can *only* be solved through OOP. At this point, I can't resist myself from quoting Joe Armstrong (creator of Erlang language) because it always makes me laugh: -

<br>

>“Because the problem with object-oriented languages is they've got all this implicit environment that they carry around with them. You wanted a banana but what you got was a gorilla holding the banana and the entire jungle.”

<br>

OOP is merely a programming paradigm where we think differently about data and functions/methods which work on data. One other paradigm is **imperative programming**. Languages like C are based on imperative programming paradigm while JAVA, C++ are OOP pardigm based. Python supports both paradigms. But how? The key difference between them is that in imperative programming, data and functions are separate from each other but in OOP, they are entwined. Think about a dog. As soon as you think about a dog, the idea that "All dogs bark" almost immediately comes to mind. The function "barking" is attached to dogs. **God (or Nature) attaches this act of barking as soon as he creates a dog object.** That is at the heart of OOP. In imperative programming, you create a dog object and then you *separately* create a 'barking' function. In this case, you can still make dog bark but it is not its inherent characterstic. 


Note that even though OOP as a paradigm exists and is talked about as if it is some concrete concept, the exact formalism of OOP varies. Besides, each language implement OOP in its own ways. Java way of doing OOP is different from that of Python. Anyways....


#### Classes and instances

A Class is a concept or blueprint. The sole object of having a class is to define things and descibe rules. It is like a standardized car manufacturing manual which helps you build actual cars. Put another way, a student is a generic term. It captures some ideas about what we mean when we refer someone as a student.  You aren't actually talking about some particular student named Peter or Steve. The actual cars you build with the help of manual are instances of a class 'car'. The actual student named 'Steve' is an instance of a class 'Student'. And this Steve guy will have all the properties and methods of a *general student* (or defined by class 'Student'). 

In Python, you define a class like this:









 





#### Classes



In [5]:
class Car:
    pass

classes are defined by using the statement `class` followed by a class name. For class names, we follow CamelCase convention (ex. - `MyClass`, `ElectricCar` etc). So far, we haven't described anything about this class `Car`. We used the `pass` as a filler because class body can't be empty. So what can we do with this class? Not much. The only thing we can do is to create instances of this classes. We create instances like this -  

In [8]:
car1 = Car()

We can create as many instances as we wish. You can use `isinstance` function to see that `car1` is an instance of class `Car`.

In [9]:
isinstance(car1, Car)

True

Alternatively, you can access `__class__` attribute of an instance to find out its class - 

In [75]:
print(car1.__class__)

<class '__main__.Car'>


In [187]:
type(car1)

<class '__main__.Car'>

You may have noticed the similarity between above and calling a function. That is how we pretended that `list()` etc are functions. Let's  use `list()` again -

In [12]:
some_list = list()
isinstance(some_list, list)

True

See? `some_list` is an instance of `list` class. 

Since everything is an object in Python, our classes and their instances are also objects and like every object, our classes and instnaces can have their own attributes and methods. For example, `list` class has its own `append` method. Methods and attributes associated with an object can be accessed by using `.` notation. You have done this many times. Let's recap - 



In [13]:
a = int(4)
isinstance(a, int)

True

In [14]:
a.numerator #numerator attribute

4

In [15]:
a.as_integer_ratio() #'as_integer_ratio' is a method 

(4, 1)

So what methods and attributes does our `Car` class have? None. Because, unlike `int` or `list`, `Car` is user defined class and we haven't added anything to it. Didn't I say that our class was pretty much useless? Well, let's add stuff to our cool `Car` class.  

In [120]:
class Car:
    wheels = 4
    
    def run(self):
        print("Car goes broom!!!")
    
car1 = Car()
car1.run()

Car goes broom!!!


In [121]:
car1.wheels, Car.wheels

(4, 4)

Now we have added few things to our `Car` class. We have added a **class attribute** `wheels` with value `4`. This attribute is defined at class level hence the name 'class attribute'. This attribute is shared by all instances. As we saw above, this attribute can be accessed by both the class and its instances. We can always change the value of this attribute - 

In [122]:
Car.wheels = 'alloyed wheels'
car1.wheels

'alloyed wheels'

In above case, we have defined the class attribute inside the class body. We can define them from outside and they, too, will be shared by all instances.  

In [123]:
Car.some_attribute = 'Foo'

In [124]:
car1.some_attribute

'Foo'

However it is recommended that you define class attributes directly in the class body unless you have some good reasons. Also note that, with in the class body, class attributes are not referenced with their qualified name - 

```Python
Class Test:
    x = 4
    y = x  #not Class.x
```    

So far, we have explicitly defined 2 class attributes (`wheels` and `some_attribute`). But Python also implicitly define some other attributes such as `__dict__` and `__bases___`

In [126]:
%pprint
dir(Car)

Pretty printing has been turned OFF


['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'run', 'some_attribute', 'wheels']

You can see user defined attributes are listed last in above list. There are many others which Python defined implicitly. We shall not dig into them for the time being. 

Another thing we added is `run()` function. In the context of OOP, they are called methods (like `append` is the method of list). Take a look at it again and notice that we have passed a strange parameter `self` to this function. Before we explain `self`, note that the first parameter for any method will always be `self`. Another thing to note that the parameter name `self` is used as a convention. You can of course use any other name in place of `self` but it is not recommended. There is a special place in hell for people who do otherwise. 

The parameter `self` refers to an instance on which method is called. When applied on an instance, the `self` argument is not passed as you have noticed in `car1.run()`. At first look, it is weird. When you write an ordinary function and run it without providing required arguments, Python complains. So what is happening here? Read on carefully - 


#### `instance.method()` is equivalent to `class.function(instance)`

Let us first understand above assertion through examples - 



In [28]:
car1.run()

Car goes broom!!!


In [30]:
Car.run(car1)

Car goes broom!!!


In [127]:
type(car1.run), type(Car.run)

(<class 'method'>, <class 'function'>)

So we see that `car1.run()` is equivalent (but not same) to `Car.run(car1)`. 

What is happening here is that when we try to run `car1.run()`, the `run()` attribute is searched in the attribute list of `car1`. But we haven't defined `run()` attribute or  any other attribute for `car1`, so it is not found. You can verify that `car1` doesn't have any attribute - 

In [32]:
car1.__dict__

{}

Python then searches for this attribute in the attribute list of class. Recall that we added 3 attributes (`wheels`, `run` and `some_attribute`) to our `Car` class. So, `run` attribute is found here. How do we access it? Of course by `.` notation. But this attribute is actually a function which requires a parameter `self`. And what is the value of `self` here? It is `car1` because `self` refers to the current instance on which we are applying the method. So `car1.run()` translate to `Car.run(car1)` behind the curtains. 

1. `car1.run()` -> `car1` doesn't have any attribute `run()`. So it is searched in its class which is `Car`.
2. `run` is the attribute of `Car` -> It is found in the attribute list of `Car` where this attribute is defined as a function. 
3. Accessing this through dot notation -> `Car.run(self)`
4. `Run Car.run(car1)`

You have actually done this even before you learned any OOP. Didn't I tell you were using OOP all along? See following example - 

In [35]:
some_list = list()  #a is an instance of of `list` class

We created a fresh instance of list with name `some_list`. Note that this instance, per se, doesn't have any attribute. In fact, `list` class doesn't allow to add any attribute to its instances or itself. 

In [37]:
some_list.aa = 33  ##not allowed hence the error

AttributeError: 'list' object has no attribute 'aa'

In [39]:
some_list.append(2) #some_list doesn't have any attribute `append` but `list` class does. 

In [41]:
some_list

[2]

In [43]:
'append' in list.__dict__

True

In fact, if you have done `list.append(some_list, 2)` instead of `some_list.append(2)`, you would have got the same result. In the same vein, `Car.run(car1)` is equivalent to `car1.run()`. 

In case of `Car.run(car1)`, `run` is **unbounded** function while in case of `car1.run()`, it is an **bounded function**. [See also](https://stackoverflow.com/questions/6083090/in-python-whats-difference-between-some-string-lower-and-str-lowersome-stri?utm_source=pocket_mylist)

**When an attribute for an instance is searched, it is first searched in instance's attribute-list. If not found there, it is then searched in the attribute-list of respective class and so on**

Recall that - 

In [46]:
car1.wheels

'alloyed wheels'

In this case, too, `wheels` attribute isn't defined at instance level. It is defined at class level. So when we run `car1.wheels`, `wheels` is searched in instance's attribute list. Since it is not found there, it is then searched at class level and it is found there so `car1.wheels` is equivalent to `Car.wheels`. 

In [47]:
car1.wheels is Car.wheels

True

#### Instance attributes

Let us review the example we were working on -

In [48]:
class Car:
    wheels = 4
    
    def run(self):
        print("Car goes broom!!!")

So far, we have added a class attribute `wheels` (ignoring `some_attribute` which we added externally) and a class method. These 2 attributes are shared by all instances. But instances can have their own attributes. After all not all cars are going to look same. Some will be from Ford and some will be from Tesla and so on. Similarily they will come in different colors. So how do we add attributes to instances?

**`__init__` magic method**:

The `__init__` method is called constructor (or initializer). What it does is to initialize an instance with its initial state. This method run automatically every time an instance is created. Let us see how it works  - 

In [1]:
class Car:
    wheels = 4
    
#    def __init__(self, make, color):
 #       self.make_type = make
  #      self.color_type = color
    
    def run(self, make, color):
        print("%s %s Car goes broom!!!" %(color, make))
        
car = Car()
car.run('Ford', 'red')        

red Ford Car goes broom!!!


Although we provided a red Ford car, our `car` instance doesn't have any `color` or `make` attribute. It'd be nice if we can get something like `car.color = red` and `car.make = Ford`.

In [135]:
class Car:
    wheels = 4
    
    def run(self, make, color):
        self.make_type = make
        self.color_type = color
        print("%s %s Car goes broom!!!" %(self.color_type, self.make_type))
        
car = Car()
car.run('Ford', 'red')        

red Ford Car goes broom!!!


In [136]:
car.make_type, car.color_type

('Ford', 'red')

This is better. However, this can be done in much better way - 

In [57]:
class Car:
    wheels = 4
    
    def __init__(self, make, color):
        self.make_type = make
        self.color_type = color
    
    def run(self):
        print("Car goes broom!!!")

In [58]:
car1 = Car('Ford', 'red')
car2 = Car('Tesla', 'black')
car3 = Car('GM', 'white')

In [59]:
print(car1.make_type, car1.color_type)
print(car2.make_type, car2.color_type)
print(car3.make_type, car3.color_type)


Ford red
Tesla black
GM white


We added `__init__` method to our class. This method takes three parameters with `self` being first. In the body of this method, we wrote -

```Python
self.make_type = make
self.color_type = color
```

What we are doing here is that we are defining 2 new instance attributes `make_type` and `color_type` and we assign these 2 attributes the value of `make` and `color` parameters respectively. `__init__` method is called automatically when you create an instance, all you have to do is to provide arguments `make` and `color` when you create an instance. That is, when we run

    >>>`car1 = Car('Ford','red')`
    
an instance `car1` is created. After this, the arguments `Ford` and `red` is automatically passed to `__init__` function which in turn sets instance attributes - 

    car1.make_type = 'Ford'
    car1.color_type = 'red'


If you have read about Python OOP somewhere else, you may have seen that people usually reuse `__init__` parameters name as attribute names like this - 

```Python
class Test:
    def __init__(self, param1, param2):
        self.param1 = param1
        self.param2 = param2
```

I haven't done this simply because it confused me a lot when I first learned Python OOP. I kept the attribute name and parameter name different so that you should know how things are working out. However from now on, I'll also reuse the parameters name. 

I mentioned that `__init__` is run automatically as soon as an instance is created. Let us see an example of this - 

        




In [63]:
class Test:
    
    def __init__(self):
        print('New instance %s is created' %self)

In [65]:
foo = Test()

New instance <__main__.Test object at 0x0000002E7BF57130> is created


See? All you did is to create a new instance and the `print` function was automatically executed.

Back to instance attributes. Now our instances have their own attributes. Before that, the `__dict__` attribute of our instances returned empty dictionary. Now it won't.

In [66]:
car1.__dict__

{'make_type': 'Ford', 'color_type': 'red'}

Just like class attribute, we can add instance attribute externally - 

In [67]:
car1.fuel = 'Diesel'

In [68]:
car1.fuel

'Diesel'

In [70]:
car1.__dict__

{'make_type': 'Ford', 'color_type': 'red', 'fuel': 'Diesel'}

What if an instance has an attribute with same name as class attribute? If you were careful during earlier sections, you'd recall that attribute is first searched in instance attribute list, then in class attribute list. 


In [71]:
car2.wheels = 'Generic'

In [72]:
car2.wheels

'Generic'

In [73]:
car1.wheels

4

This shows that if the same attribute name occurs in both an instance and in a class, then attribute lookup prioritizes the instance. In above case, only `car1` has its own `wheels` attribute. As for `car2`, it will still use class attribute. 




**Return value of `__init__` is always `None`** so be careful your `__init__` shouldn't return anything else -  

In [119]:
class Foo:
    def __init__(self):
        print('Hi')
        return 1
    
foo = Foo()    

Hi


TypeError: __init__() should return None, not 'int'

**`__init__`** function is executed as soon as an instance of a class created. See below - 

In [128]:
class Test:
    def __init__(self):
        print("Test id is %d" %id(self)) 
        
x = Test()
y = Test()*10

Test id is 199677410464
Test id is 199677408064


TypeError: unsupported operand type(s) for *: 'Test' and 'int'

Above program shows that object is instantiated before it is assigned to any variable. Line 1 runs fine. Line 2 produces `TypeError` because of wrong multiplication. Here instance was created (as shown by `id()` function) but its product with 10 produced error and nothing was assigned to `y`. Error happens only after instance is created and before instance is assigned a name 'y'. If this program is run interactively, `print(x)` command will run successfully but `print(y)` command will raise `NameError`. 

In [129]:
print(x)
print(y)

NameError: name 'y' is not defined

#### Inheritance

Let's write a generic OOP code which is exactly similar to what we have written so far (no more car stuff).



In [176]:
class A:
    
    bar = 'barbar'
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is {}".format(self.value))

Now we can write a class `B` which inherits from `A`. We'll see what this means. 

In [177]:
class B(A):
    pass
    
b = B(5)    

In [179]:
B.__bases__ #__bases__ gives a tuple of parent classes

(<class '__main__.A'>,)

In [154]:
b1 = B()

TypeError: __init__() missing 1 required positional argument: 'value'

In [155]:
b.bar

'barbar'

What we are doing here is that we created a class `B` which inherits attributes from class `A`. By executing `B(A)`, we are telling Python that our class `B` is a subclass of `A`. In the body of class `B`, we didn't really put anything just to keep things simple. We can always add stuff in `B` in future. 

So what happens when we run `b = B(5)`? 

Since `B` is a subclass of `A`, `B` has access to every attributes defined in `A`. If an attribute or method isn't found in `B`, it will be looked up in `A`. In above case, an instance is created and immediately after it is created, it looks for `__init__` method which we haven't provided in `B`. In that case, it is searched in `A` where it is found and executed. 

Attributes look-up works in the same way - 


In [156]:
b.bar

'barbar'

In [157]:
b.func()

This is 5


Another common use of inheritance is that of calling parent's class `__init__` method. For example - 

In [158]:
class A:
    
    bar = 'barbar'
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is {}".format(self.value))
        
class B(A):
    
    def __init__(self, value, name, group):
        self.name = name
        self.group = group
        A.__init__(self, value)    #part of the task was delegated to parent's `init` method
        
    def show(self):
        print("%s has value %d and belongs to group %s" %(self.name, self.value, self.group))
        
        
b = B(8, 'Mac', 'Top tier') 
b.show()

Mac has value 8 and belongs to group Top tier


Class `A` instances are initialized with only one attribute (`value`) but instances of class `B` have 2 additional attributes (`name` and `group`). Since `B` inherits from `A`, it can always use access `A`s attributes (and methods). This is known as **delegation**. So we say that `B`'s `__init__` method has delegated part of its task to `A`s `__init__` method. This way, we were able to avoid the repetition of task. Always remember the **DRY (DON'T REPEAT YOURSELF)** principle.





#### Method overriding

Above `b` is an instance of `B` but it was able to access `func` method of class `A` because there was no `func` defined in `B`. 

Let us define `B`'s own `func` method -  

In [97]:
class B(A):
    def func(self):
        print("This is new method")
        
b = B(4)
b.func()

This is new method


But what if `b`  want to use the `func` method of `A`?


In [100]:
A.func(b) 

This is 4


One useful aspect of method overriding is that sometimes your subclass function want to delegates part of it task to parent class function with same name. For example -   

In [108]:
class B(A):
    def func(self):
        print('Hi')
        A.func(self)
        
b = B(4)
b.func()

Hi
This is 4


In above example of class `A` and class `B`, you may have noticed that we haven't added any new attribute in class `B`. Instead, class `B` is using the the `__init__` of class `A`. However, this wouldn't work if we wish to add new attributes to subclass. 

In [117]:
class A:
    
    bar = 'barbar'
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is {}".format(self.value))
        
class B(A):
    
    def __init__(self, value, name):
        A.__init__(self, value)
        self.name = name
        
    def func(self):
        print(self.name, self.value)
        
b = B('Foo', 5)
b.func()

5 Foo


In this case, we have provided one new instance variable `name` which will be the value of `name` attribute of class `B` instances. In this case, we have to initialize it separately which means we have to provide `__init__` in class `B`. Again, if we provide this method in class `B`, `value` attribute won't be initialized as `A`'s `__init__` won't be called automatically here. For this, we have to explicitly call `A`s `__init__` method.  

####  Multiple Inheritance and `super()`

In above examples, there was only one parent class and one child class so things were pretty simple. Python also supports multiple inheritance. A child class can inherits from more than 1 parent class. See a typical example below -

```Python
class A:
    pass

class B(A):
    pass

class C(A):
    pass

class D(B,C):
    pass
```

So how does attribute lookup work in multiple inheritance? In general, you can think of the search for attributes inherited from a parent class as depth-first, left-to-right, not searching twice in the same class where there is an overlap in the hierarchy. 

Let's see a very basic example to illustrate this -  


    

In [22]:
class A():
    x = 'a' 
    
class B(A): 
    pass

class C(A): 
    x = 'c'

class D(B, C): 
    pass
 
D.x

'c'

In finding `D.x`, the attribute `x` is first searched in `D` (depth first), then in `B` (parent classes, left to right) and then in `C` where it is found. This searching concept is known as **method resolution order (MRO)**. You can always use the `__mro__` attribute of a class to find out method resolution order. This works for attribute lookup as well. 

In [23]:
D.__mro__

(__main__.D, __main__.B, __main__.C, __main__.A, object)

You can notice that this order preserves the principle of 'depth first, then left to right parent classes'. 

### `super()`

When we introduced the concept of inheritance, we did following example - 



In [142]:
class A:
    
    bar = 'barbar'
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is {}".format(self.value))
        
class B(A):
    def func(self):
        print('Hi')
        A.func(self)
        
b = B(4)
b.func()        

Hi
This is 4


In above example, recall that we defined a `func` method in class `B` which in turn calls the parent class (in our case, `A`) `func` method. To call the parent class method in child class, we accessed it through `.` notation (`A.func()`). In this case we know that `B` has only one base class so it was easy to use base class's method. However, this way of hard-coded call to base class's method is often undesirable, error-prone and offers  limited capability. 

Above example is fairly simple example of single inheritance. Nothing complicated here. But what if we change the name class `A` to class `C`? What if we come up with a new class `C` and make it the base of `B`? What if `B` has multiple base classes? In all these cases, you simply can't always call parent's method by hard-coded call. It doesn't offer any flexibility. It may even lead to wrong solution.


In [145]:
class A:
    
    bar = 'barbar'
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is {}".format(self.value))
        
class C:
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is different function")   
        
class B(C, A):
    def func(self):
        print('Hi')
        A.func(self)
        
b = B(4)
b.func()        

Hi
This is 4


In above example, we only added one more class `C` and `B` now has 2 base classes. You still want to call `func` method of *next in line* base class. But you had actually hardcoded this call to `A`s `func` method. The expected output is -

```
Hi
This is different function
```

But you aren't getting correct output because you are not calling correct next base class's method. 

To address these kind of problems (and many more), `super()` was introduced. Let's see how it works - 

In [161]:
class A:
    
    bar = 'barbar'
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is {}".format(self.value))
        
class B(A):
    def func(self):
        print('Hi')
        super().func() #A is replaced with super(). func() no longer need 'self' argument
        
b = B(4)
b.func()  

Hi
This is 4


In [162]:
B.__mro__

(<class '__main__.B'>, <class '__main__.A'>, <class 'object'>)

In [166]:
class A:
    
    bar = 'barbar'
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is {}".format(self.value))
        
class C:
    
    def __init__(self, value):
        self.value = value
        
    def func(self):
        print("This is different function")   
        
class B(C, A):
    def func(self):
        print('Hi')
        super().func()  #super() in place of 'A'.
        
b = B(4)
b.func()        

Hi
This is different function


In [160]:
B.__mro__

(<class '__main__.B'>, <class '__main__.C'>, <class '__main__.A'>, <class 'object'>)

In both cases, `super()` searched the method `func` in next-in-line parent class as described by the class's `__mro__` attribute. You can see that in former case, MRO wrt class `B` was `B --> A --> object` while in later case, MRO wrt same class `B` was `B --> C --> A --> object`. Using `super()` makes sure that it delegates the method calls to the class as described by MRO for class in which `super()` was used. 

**Note carefully** that, in last example, the MRO wrt class `B` was `B --> C --> A --> object` but `super()` actually started searching `func` from `C`. It skipped the class where it was called (in this case, `B`).


The function signature of `super()` is **`super([type, [object_or_type])`** and this returns a proxy object. 

If no arguments are provided, then `super()` is equivalent to `super(present_class, self)`. For above example `super()` is equivalent to `super(B, self)`. `super(B, self)` indicates that `self` is an instance of `B` and, more importantly, the search starts from the class right after the `B` in MRO wrt `B`.

See below example - 






In [165]:
class A:
    def test(self):
        print('A')
        
class B(A):
    def test(self):
        print('B')
        
class C(A):
    def test(self):
        print('C')
        
class D(B, C):
    def test(self):
        super(C, self).test() #search starts after `C` in D.__mro__ .
        
#keep changing C to B or D. 
d = D()
d.test()

A


You can see from these examples that `super()` offers a lot of flexibility. Moreover, `__mro__` is a dynmaic attribute and can change whenever class hiearchy is changed. This means that `super()` can use the updated hiearchy because it use `__mro__` attribute for searching. 

**Cautionary Note** Many people initially develop this incorrect mental model that `super().some_method()` is equivalent to `base.some_method(self)`. I'll be honest that I, too, developed this incorrect mental model. This rather unintuitive behaviour of `super()` was the talking point of famous blog [Python's Super Considered Harmful](https://fuhm.net/super-harmful/). This blog caused Raymond Hettinger (he is Python's core developer) to write [Python’s super() considered super!](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/). 


Let me clarify what I mean by incorrect mental model of `super()`. See following snippets - 

```Python 
class A:
    def test(self):
        print("Hi")
        
class B(A):
    def test(self):
        A.test(self)
```
does the same thing as


```Python 
class A:
    def test(self):
        print("Hi")
        
class B(A):
    def test(self):
        super().test()
```

Be careful that `super().test()` is not the same thing as `A.test(self)`. 

See following examples - 


In [169]:
#some people think it will output `A` wrongly assuming that
#super().setmethod() in class B(A) will delegate the call to A's setmethod. 

class A:
    def setmethod(self):
        print('A')
        
class B(A):
    def setmethod(self):
        super().setmethod() #super()refers to next in D.__mro__ in case of d.setmethod()
        
class C(A):
    def setmethod(self):
        print('C')
        
class D(B,C):
    def setmethod(self):
        super().setmethod()
        
d = D()
d.setmethod()        

C


In [170]:
#even better example


class Base():
    def __init__(self):
        print("Base init'ed")

class ChildA(Base):
    def __init__(self):
        print("ChildA init'ed")
        Base.__init__(self)       #Hardcoded call to Base init

class ChildB(Base):
    def __init__(self):
        print("ChildB init'ed")
        super().__init__()        #uses super()
        
class UserDependency(Base):
    def __init__(self):
        print("UserDependency init'ed")
        super().__init__()
        
class UserA(ChildA, UserDependency):
    def __init__(self):
        print("UserA init'ed")
        super().__init__()

class UserB(ChildB, UserDependency):
    def __init__(self):
        print("UserB init'ed")
        super().__init__()
        
UserA()        

UserA init'ed
ChildA init'ed
Base init'ed


In [171]:
UserB()

UserB init'ed
ChildB init'ed
UserDependency init'ed
Base init'ed


In [173]:
class A:
    def __init__(self,a):
        self.a = a
        
    def test(self):
        print("Class A method is run.")

        
class B(A):
    def test(self):
        print('B')
        super().test()
        print("Class B method is run")
        
class C(A):        
    def test(self):
        print('C')
        super().test()
        print("Class C method is run")
    
class D(B, C):        
    def test(self):
        print('D')
        super().test()
        print("Class D method is run")

d = D(2)   
d.test()

D
B
C
Class A method is run.
Class C method is run
Class B method is run
Class D method is run


In [174]:
class A:
    def __init__(self):
        print('A')
        
class B(A):
    def __init__(self):
        print('B')
        super().__init__()
        
class C(A):
    def __init__(self):
        print('C')
        super().__init__()
                
class D(B, C):
    def __init__(self):
        print('D')
        super().__init__()
        
d = D()        

D
B
C
A


In [175]:
#similar to above, except that print command now comes after super()

class A:
    def __init__(self):
        print('A')
        
class B(A):
    def __init__(self):
        super().__init__()
        print('B')
        
class C(A):
    def __init__(self):
        super().__init__()
        print('C')
                
class D(B, C):
    def __init__(self):
        super().__init__()
        print('D')
d = D()        

# D's super() moves to B's super which in turns moves to C's super which in turns moves to A's __init__

A
C
B
D


Sources and further reading (readers may find them a bit advanced materials)-

[The Python 2.3 Method Resolution Order](https://www.python.org/download/releases/2.3/mro/)

[Method Resolution Order (MRO) in new-style classes?](https://stackoverflow.com/questions/1848474/method-resolution-order-mro-in-new-style-classes/27670178?utm_source=pocket_mylist)

[Understanding Python super() with __init__() methods](https://stackoverflow.com/questions/576169/understanding-python-super-with-init-methods/27134600?utm_source=pocket_mylist)

[What does 'super' do in Python? - difference between super().__init__() and explicit superclass __init__()](https://stackoverflow.com/questions/222877/what-does-super-do-in-python-difference-between-super-init-and-expl/33469090#33469090)

[Python's Super considered harmful](https://fuhm.net/super-harmful/)

[Python’s super() considered super!](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/) - This one is classic. 

#### Encapsulation, Private Attributes and Data Hiding

From [Wikipedia](https://en.wikipedia.org/wiki/Object-oriented_programming#Encapsulation) - 

> Encapsulation is an object-oriented programming concept that binds together the data and functions that manipulate the data, and that keeps both safe from outside interference and misuse. Data encapsulation led to the important OOP concept of data hiding. ...

Often times you write classes but you don't really want to let other people access/modify its internals. This concept of data hinding is known as encapsulation.  

For example - 

In [198]:
class A:
    def __init__(self, name):
        self.name = name
                
a = A('Sam')
a.name

'Sam'

In [199]:
a.name = 'Mayank'

In [200]:
a.name

'Mayank'

In above example, the `name` attribute was accessible from outside and we could modify it. However, this may not always be desirable. In order to protect our classes from misuses and undesired modifications, some sort of mechanism is needed. Although languages like Java has strict mechanism in place to achieve encapsulation, Python doesn't have that sort of mechanism. Python only has *conventions* which are enforced by *consenting adults*. 

By  Alex Martelli [Source](https://stackoverflow.com/questions/1547145/defining-private-module-functions-in-python)- 
```
In Python, "privacy" depends on "consenting adults'" levels of agreement - you can't force it (any more than you can in real life;-). A single leading underscore means you're not supposed to access it "from the outside" -- two leading underscores (w/o trailing underscores) carry the message even more forcefully... but, in the end, it still depends on social convention and consensus: Python's introspection is forceful enough that you can't handcuff every other programmer in the world to respect your wishes.
```



Another excrept [Source](https://mail.python.org/pipermail/tutor/2003-October/025932.html) -

```
 ..."we are all consenting adults here"... 
This expression is also used in the object-oriented python
literature to explain python's attitudes about private class
members, which python doesn't have. 

When you create an instance of some class there is nothing to
prevent you from poking around inside and using various internal,
private methods that are (a) necessary for the class to function,
BUT (b) not intended for direct use/access.

Nothing is really private in python. No class or class instance can
keep you away from all what's inside (this makes introspection
possible and powerful). Python trusts you. It says "hey, if you want
to go poking around in dark places, I'm gonna trust that you've got
a good reason and you're not making trouble."

After all, we're all consenting adults here.

C++ and Java don't have this philosophy (not to the same extent).
They allow you create private methods and static members. 

Perl culture is like python in this respect, but Perl expresses the
sentiment a bit differently. As the Camel book puts it,

  "a Perl module would prefer that you stayed out of its living room
  because you weren't invited, not because it has a shotgun."

But the sentiment is identical.
```
And now from Guido himself - 

```
"main reason for making (nearly) everything discoverable was debugging: when debugging you often need to break through the abstractions"
```

In gist, nothing is actually hidden in Python. Python only has conventions and since we are 'consenting adults', Python trusts us with our good intentions. 

Directly copied from [Official Python Tutorial](https://docs.python.org/3/tutorial/classes.html#private-variables) -

- A name prefixed with an underscore (e.g. `_spam`) should be treated as a non-public part of the API (whether it is a function, a method or a data member). It should be considered an implementation detail and subject to change without notice.


- Since there is a valid use-case for class-private members (namely to avoid name clashes of names with names defined by subclasses), there is limited support for such a mechanism, called *name mangling*. Any identifier of the form `__spam` (at least two leading underscores, at most one trailing underscore) is textually replaced with `_classname__spam`, where `classname` is the current class name with leading underscore(s) stripped. This mangling is done without regard to the syntactic position of the identifier, as long as it occurs within the definition of a class.

Let us see what all these things means.

In [201]:
class Encapsulation():
    def __init__(self, a, b, c):
        self.public = a
        self._protected = b
        self.__private = c
        print(self.__private)  #from inside of class, you can access it.
        
A = Encapsulation(1,2,3)        

3


In [202]:
print(A.public)
print(A._protected)  # it is accessible. 
print(A.__private)   #from outside, this attribute isn't accessible as __private is now _Encapsulation__private

1
2


AttributeError: 'Encapsulation' object has no attribute '__private'

In [203]:
A._Encapsulation__private #name-mangling in action. 

3

In [204]:
class Foo:
    def __init__(self, name):
        self.__name = name
    def setname(self):
        return self.__name
    
bar = Foo('Mayank')

bar.setname()  #class methods can access it. 

'Mayank'

In [205]:
bar.__name

AttributeError: 'Foo' object has no attribute '__name'

In [206]:
bar._Foo__name

'Mayank'

In [32]:
##another example
class D:
    __value =  5
    
class E(D):
    def printf(self):
        print(self.__value)
     
    
a = E()
a.printf()

AttributeError: 'E' object has no attribute '_E__value'

In [209]:
class MyClass:
    def myPublicMethod(self):
            print('public method')
    def __myPrivateMethod(self):
            print('this is private!!')

obj = MyClass()

obj.myPublicMethod()

public method


In [210]:
obj.myPrivateMethod()

AttributeError: 'MyClass' object has no attribute 'myPrivateMethod'

From Python Essential Reference book – 

By default, all attributes and methods of a class are “public.”This means that they are all accessible without any restrictions. It also implies that everything defined in a base class is inherited and accessible within a derived class.This behavior is often undesirable in object-oriented applications because it exposes the internal implementation of an object and can lead to namespace conflicts between objects defined in a derived class and those defined in a base class. To fix this problem, all names in a class that start with a double underscore, such as` __Foo`, are automatically mangled to form a new name of the form `_Classname__Foo`. This effectively provides a way for a class to have private attributes and methods because private names used in a derived class won’t collide with the same private names used in a base class. 

Here is an example -
```python
class A(object):
    def __init__(self):
        self.__X = 3       # Mangled to self._A__X
    def __spam(self):      # Mangled to _A__spam()
        pass
    def bar(self):
        self.__spam()      # Only calls A.__spam()

class B(A):
    def __init__(self):
        A.__init__(self)
        self.__X = 37      # Mangled to self._B__X
    def __spam(self):      # Mangled to _B__spam()
        pass
```

Although this scheme provides the illusion of data hiding, there’s no strict mechanism in place to actually prevent access to the “private” attributes of a class. In particular, if the name of the class and corresponding private attribute are known, they can be accessed using the mangled name.


### `__slots__`

By default, instances of classes have a dictionary for attribute storage.  This wastes space for objects having very few instance variables.  The space consumption can become acute when creating large numbers of instances.

The default can be overridden by defining `__slots__` in a class definition.

The `__slots__` declaration takes a sequence of instance variables and reserves just enough space in each instance to hold a value for each variable.  Space is saved because `__dict__` is not created for each instance.

So we achieve - 

 - Faster attribute access
 - Memory saving

[Further reading](https://stackoverflow.com/questions/472000/usage-of-slots)

In [218]:
class A:
    
    def __init__(self, name, value, group):
        self.name = name
        self.value = value
        self.group = group
        
a = A('Same', 44, 'Top')
a.__dict__

{'name': 'Same', 'value': 44, 'group': 'Top'}

In [219]:
a.attr = 'something'
a.__dict__

{'name': 'Same', 'value': 44, 'group': 'Top', 'attr': 'something'}

In [220]:
a.__slots__

AttributeError: 'A' object has no attribute '__slots__'

In [215]:
class A:
    
    __slots__ = ['name', 'value', 'group']
    
    def __init__(self, name, value, group):
        self.name = name
        self.value = value
        self.group = group
        
a = A('Same', 44, 'Top')

a.__dict__ #when slots are defined, __dict__ becomes unavailable

AttributeError: 'A' object has no attribute '__dict__'

In [216]:
a.attr = 'not a chance' #no other attribute, except for allowed by slots, is possible
a.attr

AttributeError: 'A' object has no attribute 'attr'

In [217]:
a.__slots__

['name', 'value', 'group']

### `@classmethod` and `@staticmethod`

Note - Since we haven't covered decorators, you may be puzzled by this `@` prefixes in above terms. We will cover them in future. 

First, a same old boring example -


In [228]:
class A:
    
    def test(self):
        print('Hi')
        
a = A()

a.test() #this is how method is run

Hi


In [229]:
A.test(a) #unbounded function

Hi


In [230]:
A.test() #not a chance

TypeError: test() missing 1 required positional argument: 'self'

Whether you use `test` as bounded function (that is, you run it as `a.test()`) or as unbounded function (`A.test(a)`), you need to have an instance of the class. You are actually using `test` on *per instance* basis. After all, class members are meant to be used by instances. The way you define a method, the first parameter is always set as `self`. 

Class methods, on the other hand, don't need instances. Instead of `self` (instance), they have `cls` (class) as first parameter. So how does that work? You use `@classmethod` decorator as shown below -   



In [231]:
class A:
    
    @classmethod
    def test(cls):
        print('Hi')
        
A.test()        

Hi


In [232]:
a = A()
a.test()  #cls is automatically passed as first argument to test()

Hi


In [233]:
A.test(a) #if test() were instance method, this would've run

TypeError: test() takes 1 positional argument but 2 were given

Note also that there is no way class methods can access or manipulate instance variables. However, they can access class variables. 


In [235]:
class Times():
    factor = 3
    @classmethod
    def mul(cls,x):
        return cls.factor*x 
    
Times.mul(3)    

9

In [236]:
Times.__dict__

mappingproxy({'__module__': '__main__', 'factor': 3, 'mul': <classmethod object at 0x0000002E7DB3A340>, '__dict__': <attribute '__dict__' of 'Times' objects>, '__weakref__': <attribute '__weakref__' of 'Times' objects>, '__doc__': None})

Class methods can be inherited. In that case, `cls` refers to child class. 

In [237]:
class Times():
    factor = 1
    @classmethod
    def mul(cls,x):
        return cls.factor*x

class TwoTimes(Times):
    factor = 2

x = TwoTimes.mul(4)    

print(x)

8


### `@staticmethod`

In [256]:
class Test:

    @staticmethod
    def testmethod():
        print('Hi')
    
    def __init__(self,number):
        self.number = number

    def setmethod(self):
        print(self.number)    

Test.testmethod()       

Hi


### `@property`

In [257]:
import math

class Circle:
    def __init__(self,radius):
        self.radius = radius

    @property
    def area(self):
        return math.pi*self.radius**2

    @property
    def perimeter(self):
        return 2*math.pi*self.radius

c = Circle(4)
c.radius



4

In [258]:
c.perimeter, c.area

(25.132741228718345, 50.26548245743669)

In [259]:
c.perimeter =  5

AttributeError: can't set attribute

As we know, instances of a class has attributes and methods bound to them. To access attributes and methods, we use dot notation. To access an attribute, we write `object.attribute` while to apply a method, we write `object.method()`. However, unlike methods, we can always change the value of attribute as shown above (c.radius = 5). In above program, if we don’t use `@property` decorator, we would apply method like this: `c.perimeter()`. But by using `@property` decorator, we get rid of those parentheses used after a method. So, now we can write `c.perimeter` instead of `c.perimeter()`. However, as said earlier, we can’t change the value of `c.perimeter` which is obvious. This is an example of making programming interface as uniform as possible.(Uniform Access Principle)	

#### `__repr__`

In [238]:
class Test:
	def __init__(self,value):
		self.value = value
	def __repr__(self):
		return 'value for current instance = %s' % self.value

a = Test(5)
a

value for current instance = 5

#### `__call__`

In [239]:
class Foo:
    def __call__(self):
        print('Hi')
        
bar = Foo()
bar()


Hi


#### `__del__`

In [240]:
class Person:
    def __init__(self, name):
        self.name = name
        print(self.name)
        
    def sayhello(self):
        print("Hi", self.name)
        
    def __del__(self):
        print("bye", self.name)
        
A = Person("Mayank")

A.sayhello()        
        

Mayank
Hi Mayank


In [242]:
del A

bye Mayank


In [245]:
class Employee:
    
    empCount = 0
    
    def __init__(self):
        Employee.empCount += 1
        print(Employee.empCount)
        print(id(self))

    def __del__(self):
        Employee.empCount -= 1
        print(Employee.empCount)
        print(id(self))
        
emp1 = Employee()
emp2 = Employee()

1
199677415280
2
199677413888


In [246]:
del emp1

1
199677415280


In [247]:
del emp2

0
199677413888


In [248]:
Employee.empCount

0

#### `__add__`



In [243]:
class Strings:
    def __init__(self,a):
        self.a = a
        
    def __add__(self, other):
        return self.a + other.a
    
aa = Strings('x')
ba = Strings('y')

aa+ba, aa.a, ba.a

('xy', 'x', 'y')

In [244]:
class Foo:
    def __init__(self,x,y):
        self.x = x
        self.y = y
        
    def __add__(self, other):
        self.x = self.x + other.x
        self.y = self.y + other.y
        return self.x, self.y
    
a = Foo(3,4)
b = Foo(4,5)

a + b


(7, 9)

Some random examples - 

In [249]:
class Foo:
    def __init__(self, door):
        self.door = door
        
    def test(self):
        return self.door.bar()
    
class Baz:
    def bar(self):
        print('Hi')
        
        
baz = Baz()
foo = Foo(baz)
foo.test()        

Hi


In [16]:
class Customer:
    def __init__(self, name, balance):
        self.name = name
        self.balance =balance
    
    def deposit(self, amount):
        self.amount = amount
        self.balance = self.balance + self.amount
        print(self.balance)
        
    def test(self):
        #print(amount)  #wouldn't work
        print(self.amount)
        
        
customer1 = Customer("Sam", 1000)
customer2 = Customer("Peter", 500)

customer1.deposit(500)
customer2.deposit(500) 

1500
1000


In [17]:
customer1.test()

500
